### ISSUE TITLE
Plan construction failed when installing IHaskell

### ISSUE THREAD

**Issue by marmalodak** [gibiansky/IHaskell#717] opened 2017-05-14 18:08 UTC
HOME=/mnt/myth/john/projects/jupyter/haskell/stack stack --stack-root /mnt/myth/john/projects/jupyter/haskell/stack --no-system-ghc --jobs 8 --color auto --verbosity debug install ihaskell
    Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0

...

    2017-05-14 07:52:55.921356: [debug] Constructing the build plan
    @(Stack/Build/ConstructPlan.hs:158:5)
    2017-05-14 07:52:56.017975: [error]
    Error: While constructing the build plan, the following exceptions were encountered:

    In the dependencies for ihaskell-0.8.4.0:
        aeson-1.0.2.1 must match >=0.7 && <0.12 (latest applicable is 0.11.3.0)
        base-4.9.1.0 must match >=4.6 && <4.9 (latest applicable is 4.8.2.0)
        bin-package-db must match -any, but the stack configuration has no specified version
        ghc-parser must match >=0.1.7, but the stack configuration has no specified version (latest applicable is 0.1.8.0)
        haskell-src-exts-1.18.2 must match >=1.16 && <1.18 (latest applicable is 1.17.1)
        http-client-0.5.6.1 must match ==0.4.* (latest applicable is 0.4.31.2)
        http-client-tls-0.3.4.1 must match ==0.2.* (latest applicable is 0.2.4.1)
        ipython-kernel must match >=0.7, but the stack configuration has no specified version (latest applicable is 0.8.4.0)

    Recommended action: try adding the following to your extra-deps in /mnt/myth/john/projects/jupyter/haskell/downloads/stack-1.4.0-linux-x86_64/global-project/stack.yaml:
    - ghc-parser-0.1.8.0
    - ipython-kernel-0.8.4.0

    You may also want to try the 'stack solver' command
    @(Stack/Build/ConstructPlan.hs:197:13)
    Plan construction failed.

How do I fix this?  Invoking the solver simply gave me a different error message I didn't understand.

Please let me know if this is not the appropriate place for this question and I should take this up somewhere else. I'm totally new to Haskell and wanted to do exercises in the notebook.

**Comment by vaibhavsagar** [comment] 2017-05-15 01:32
Hey @marmalodak, IHaskell doesn't support GHC 8 yet. We're working on this but in the meantime you might want to take a look at this fork: https://github.com/abarbu/IHaskell

**Comment by marmalodak** [comment] 2017-05-15 04:21
Thank you very much for helping.

What do I have to do in my configuration so that I install a supported
version of GHC?

**Comment by vaibhavsagar** [comment] 2017-05-15 06:15
The problem is with IHaskell, not your configuration, but if you're set on installing IHaskell with `stack`, try `stack install ihaskell --resolver lts-6`

**Comment by vaibhavsagar** [comment] 2017-06-25 03:05
Hi @marmalodak, can you try again with the latest `master`?

**Comment by marmalodak** [comment] 2017-06-25 16:16
This seems to work. Is there anything specific in my notebook to try to show that it works to your satisfaction?

**Comment by vaibhavsagar** [comment] 2017-06-25 16:28
Your confirmation is enough 😄. Closing this.

**Closed by vaibhavsagar** 2017-06-25 16:28 UTC
