### ISSUE TITLE
Notebook JSON is invalid: 'header' was unexpected

### ISSUE THREAD

**Issue by jamesdbrock** [gibiansky/IHaskell#1227] opened 2021-06-14 09:50 UTC
I've been noticing errors like this:

```
[E 2021-06-14 09:44:03.493 ServerApp] Notebook JSON is invalid: Additional properties are not allowed ('header' was unexpected)
    
    Failed validating 'additionalProperties' in error:
    
    On instance['cells'][25]['outputs'][0]:
    {'ename': '',
     'evalue': '',
     'header': 'MessageHeader {mhIdentifiers = '
               '["b4497a46-0b76-40cf-9e23-e55654c...',
     'output_type': 'error',
     'traceback': ['<interactive>:1:1: error:\n'
                   '    • No instance for (Num String) ari...']}
```

but the Notebook works fine, as far as I can tell.

**Comment by vaibhavsagar** [comment] 2021-06-14 15:56
Do you have a notebook that demonstrates this issue?

**Comment by jamesdbrock** [comment] 2021-06-15 03:12
I get these errors when I open a blank notebook.

**Comment by DougBurke** [comment] 2021-06-23 17:54
I've also seen this recently but I've normally fixed the underlying problem in the notebook (such as the 'no instance for Num ...' error in @jamesdbrock's report) so I've not been able to work out a repeatable case.

**Comment by FPtje** [comment] 2022-01-14 17:18
I just hit this issue. A repeatable case can be created as follows.

- Create a new IHaskell notebook called `foo.ipynb`.
- In it, create a code cell with the following contents: `foo`
- Run that cell. The following error output will be added below it: `<interactive>:1:1: error: Variable not in scope: foo`
- In a terminal, run `jupyter execute foo.ipynb`.
- Get the following output:
```
[NbClientApp] Executing errors.ipynb
[NbClientApp] ERROR | Notebook JSON is invalid: Additional properties are not allowed ('header' was unexpected)

Failed validating 'additionalProperties' in error:

On instance['cells'][0]['outputs'][0]:
{'ename': '',
 'evalue': '',
 'header': 'MessageHeader {mhIdentifiers = '
           '["2e775aae-135e-4fed-857e-a386b42...',
 'output_type': 'error',
 'traceback': ['<interactive>:1:1: error: Variable not in scope: foo']}
[NbClientApp] Executing notebook with kernel: haskell
Press Ctrl-C again to quit kernel.
```

**Comment by FPtje** [comment] 2022-01-14 17:22
It seems like this problem causes error reporting to fail. If I create a _Python_ notebook with some error, and `jupyter execute` it, `jupyter execute` will actually exit with exit code `1`. However, in the above reproduction case, `jupyter execute` exits with exit code `0`. 

Even when running [`pytest --nbmake`](https://github.com/treebeardtech/nbmake) on the IHaskell notebook, the test succeeds stating everything is fine. For the Python notebook it shows the error and a stack trace.

**Comment by vaibhavsagar** [comment] 2022-01-15 03:23
Thanks for the repro, I think the issue is that we shouldn't be putting `header` in the error response at all so I opened https://github.com/gibiansky/IHaskell/pull/1314. However, I'm still getting an exit code `0` so I think that's a separate and unrelated issue:

```
vaibhavsagar@nixos-t480:~/repos/IHaskell$ cat Foo.ipynb 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3b7a290f",
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "<interactive>:1:1: error: Variable not in scope: foo"
     ]
    }
   ],
   "source": [
    "foo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "018d1386",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Haskell",
   "language": "haskell",
   "name": "haskell"
  },
  "language_info": {
   "codemirror_mode": "ihaskell",
   "file_extension": ".hs",
   "mimetype": "text/x-haskell",
   "name": "haskell",
   "pygments_lexer": "Haskell",
   "version": "8.10.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
vaibhavsagar@nixos-t480:~/repos/IHaskell$ $(nix-build release-8.10.nix)/bin/jupyter execute Foo.ipynb 
[NbClientApp] Executing Foo.ipynb
[NbClientApp] Executing notebook with kernel: haskell
Press Ctrl-C again to quit kernel.
vaibhavsagar@nixos-t480:~/repos/IHaskell$ echo $?
0
```

**Comment by vaibhavsagar** [comment] 2022-01-15 04:12
Closing since #1314 has been merged. I've opened https://github.com/gibiansky/IHaskell/issues/1315 to track the weird `jupyter execute` behaviour you're seeing.

**Closed by vaibhavsagar** 2022-01-15 04:12 UTC

**Comment by FPtje** [comment] 2022-01-15 13:13
Thanks a lot for the solution!
