### ISSUE TITLE
Stack solver gives dependency errors

### ISSUE THREAD

**Issue by YotaVGA** [gibiansky/IHaskell#841] opened 2018-03-18 13:06 UTC
Hi, I installed cabal-install as requested and then launched stack solver, and even without any changes in any file I obtain this:

```
stack solver
Using configuration file: stack.yaml
Populated index cache.    
The following packages are missing from the config:
- ihaskell-display/ihaskell-rlangqq/

Using cabal packages:
- ghc-parser/
- ./
- ihaskell-display/ihaskell-aeson/
- ihaskell-display/ihaskell-blaze/
- ihaskell-display/ihaskell-charts/
- ihaskell-display/ihaskell-diagrams/
- ihaskell-display/ihaskell-gnuplot/
- ihaskell-display/ihaskell-hatex/
- ihaskell-display/ihaskell-juicypixels/
- ihaskell-display/ihaskell-magic/
- ihaskell-display/ihaskell-plot/
- ihaskell-display/ihaskell-static-canvas/
- ihaskell-display/ihaskell-widgets/
- ipython-kernel/

Using resolver: lts-11.0

Warning: Installed version of cabal-install (2.0.0.1) is newer than stack has been tested with.  If you run into difficulties, consider downgrading.
         
Using compiler: ghc-8.2.2
Asking cabal to calculate a build plan...
Trying with packages from lts-11.0 and 16 external packages as hard constraints...
Attempt failed.

>>>> Cabal errors begin
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:240:21 in main:Distribution.Client.Install
cabal: Could not resolve dependencies:
trying: lens-4.16 (dependency of Chart-cairo-1.8.3)
trying: ihaskell-diagrams-0.3.2.1 (user goal)
next goal: diagrams-cairo (dependency of ihaskell-diagrams-0.3.2.1)
rejecting: diagrams-cairo-1.4 (conflict: lens==4.16, diagrams-cairo =>
lens>=3.8 && <4.16)
rejecting: diagrams-cairo-1.3.1.2, diagrams-cairo-1.3.1.1,
diagrams-cairo-1.3.1, diagrams-cairo-1.3.0.6, diagrams-cairo-1.3.0.5,
diagrams-cairo-1.3.0.4, diagrams-cairo-1.3.0.3, diagrams-cairo-1.3.0.2,
diagrams-cairo-1.3.0.1, diagrams-cairo-1.3, diagrams-cairo-1.2.0.7,
diagrams-cairo-1.2.0.6, diagrams-cairo-1.2.0.5, diagrams-cairo-1.2.0.4,
diagrams-cairo-1.2.0.3, diagrams-cairo-1.2.0.2, diagrams-cairo-1.2.0.1,
diagrams-cairo-1.2, diagrams-cairo-1.1.0.2, diagrams-cairo-1.1.0.1,
diagrams-cairo-1.1, diagrams-cairo-1.0.1.2, diagrams-cairo-1.0.1.1,
diagrams-cairo-1.0.1, diagrams-cairo-1.0, diagrams-cairo-0.7,
diagrams-cairo-0.6, diagrams-cairo-0.5.0.2, diagrams-cairo-0.5.0.1,
diagrams-cairo-0.5, diagrams-cairo-0.4, diagrams-cairo-0.3,
diagrams-cairo-0.2, diagrams-cairo-0.1.2, diagrams-cairo-0.1.1,
diagrams-cairo-0.1 (constraint from main config
/tmp/cabal-solver8699/cabal.config requires ==1.4)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: lens (154), diagrams-cairo (38),
Chart-cairo (24), ihaskell-diagrams (9), ihaskell-charts (7)
<<<< Cabal errors end

Retrying with packages from lts-11.0 and 16 external packages as preferences...
Attempt failed.

>>>> Cabal errors begin
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:240:21 in main:Distribution.Client.Install
cabal: Could not resolve dependencies:
trying: base-4.10.1.0/installed-4.1... (dependency of ghc-parser-0.2.0.2)
trying: ihaskell-static-canvas-0.1.0.0 (user goal)
next goal: static-canvas (dependency of ihaskell-static-canvas-0.1.0.0)
rejecting: static-canvas-0.2.0.3 (conflict: base==4.10.1.0/installed-4.1...,
static-canvas => base>=4.5 && <4.10)
rejecting: static-canvas-0.2.0.2, static-canvas-0.2.0.1,
static-canvas-0.2.0.0, static-canvas-0.1.0.0 (conflict:
base==4.10.1.0/installed-4.1..., static-canvas => base>=4.5 && <4.9)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base (34), ghc-parser (13),
static-canvas (6), ihaskell-static-canvas (2)
<<<< Cabal errors end

*** Failed to arrive at a workable build plan.

Solver could not resolve package dependencies.
You can try the following:
    - Update external packages with 'stack update' and try again.
    - Tweak stack.yaml and try again
        - Remove any unnecessary packages.
        - Add any missing remote packages.
        - Add extra dependencies to guide solver.
        - Adjust resolver.
```

If it can be useful, stack build returns a series of warnings that seems strictly correlated:

```
WARNING: Ignoring out of range dependency (allow-newer enabled): lens-4.16. diagrams-core requires: >=4.0 && <4.16
WARNING: Ignoring out of range dependency (allow-newer enabled): lens-4.16. diagrams-lib requires: >=4.6 && <4.16
WARNING: Ignoring out of range dependency (allow-newer enabled): lens-4.16. diagrams-contrib requires: >=4.0 && <4.16
WARNING: Ignoring out of range dependency (allow-newer enabled): lens-4.16. diagrams-svg requires: >=4.0 && <4.16
WARNING: Ignoring out of range dependency (allow-newer enabled): lens-4.16. diagrams-cairo requires: >=3.8 && <4.16
WARNING: Ignoring out of range dependency (allow-newer enabled): base-4.10.1.0. static-canvas requires: >=4.5 && <4.10
WARNING: Ignoring out of range dependency (allow-newer enabled): free-5.0.1. static-canvas requires: >=4.9 && <4.13
ihaskell-0.9.0.3: unregistering (local file changes: ihaskell.cabal)
ihaskell-aeson-0.3.0.1: unregistering (missing dependencies: ihaskell)
ihaskell-blaze-0.3.0.1: unregistering (missing dependencies: ihaskell)
ihaskell-charts-0.3.0.1: unregistering (missing dependencies: ihaskell)
ihaskell-diagrams-0.3.2.1: unregistering (missing dependencies: ihaskell)
ihaskell-gnuplot-0.1.0.1: unregistering (missing dependencies: ihaskell)
ihaskell-hatex-0.2.1.1: unregistering (missing dependencies: ihaskell)
ihaskell-juicypixels-1.1.0.1: unregistering (missing dependencies: ihaskell)
ihaskell-magic-0.3.0.1: unregistering (missing dependencies: ihaskell)
ihaskell-plot-0.3.0.1: unregistering (missing dependencies: ihaskell)
ihaskell-static-canvas-0.1.0.0: unregistering (missing dependencies: ihaskell)
ihaskell-widgets-0.2.3.2: unregistering (missing dependencies: ihaskell)
ihaskell-0.9.0.3: configure (lib + exe)
ihaskell-0.9.0.3: build (lib + exe)
ihaskell-0.9.0.3: copy/register
ihaskell-aeson-0.3.0.1: configure (lib)
ihaskell-aeson-0.3.0.1: build (lib)
ihaskell-charts-0.3.0.1: configure (lib)
ihaskell-charts-0.3.0.1: build (lib)
ihaskell-diagrams-0.3.2.1: configure (lib)
ihaskell-aeson-0.3.0.1: copy/register
ihaskell-diagrams-0.3.2.1: build (lib)
ihaskell-gnuplot-0.1.0.1: configure (lib)
ihaskell-charts-0.3.0.1: copy/register
ihaskell-gnuplot-0.1.0.1: build (lib)
ihaskell-hatex-0.2.1.1: configure (lib)
ihaskell-hatex-0.2.1.1: build (lib)
ihaskell-juicypixels-1.1.0.1: configure (lib)
ihaskell-gnuplot-0.1.0.1: copy/register
ihaskell-juicypixels-1.1.0.1: build (lib)
ihaskell-magic-0.3.0.1: configure (lib)
ihaskell-diagrams-0.3.2.1: copy/register
ihaskell-hatex-0.2.1.1: copy/register
ihaskell-magic-0.3.0.1: build (lib)
ihaskell-blaze-0.3.0.1: configure (lib)
ihaskell-juicypixels-1.1.0.1: copy/register
ihaskell-blaze-0.3.0.1: build (lib)
ihaskell-plot-0.3.0.1: configure (lib)
ihaskell-magic-0.3.0.1: copy/register
ihaskell-plot-0.3.0.1: build (lib)
ihaskell-static-canvas-0.1.0.0: configure (lib)
ihaskell-blaze-0.3.0.1: copy/register
ihaskell-static-canvas-0.1.0.0: build (lib)
ihaskell-widgets-0.2.3.2: configure (lib)
ihaskell-plot-0.3.0.1: copy/register
ihaskell-widgets-0.2.3.2: build (lib)
ihaskell-static-canvas-0.1.0.0: copy/register
ihaskell-widgets-0.2.3.2: copy/register
Completed 12 action(s).
Log files have been written to: /home/totoro/apps/ihaskell/IHaskell/.stack-work/logs/
```

stack solver && stack build is the way you suggest to install other modules, so I think there is something wrong here

**Comment by vaibhavsagar** [comment] 2018-03-18 15:01
Have you already successfully installed IHaskell? The instructions for doing that are https://github.com/gibiansky/IHaskell#linux. I also don't see where we suggest using `cabal-install`.

**Comment by vaibhavsagar** [comment] 2018-03-18 15:11
Looking again, I think the issue is that we're leaning heavily on `allow-newer: true` in `stack.yaml` and `stack solver` isn't working well with that option being set. The underlying problem seems to be restrictive upper bounds on `lens` in some of our dependencies, which will hopefully get fixed in the next week or two. In the meantime I'd suggest using a different resolver, such as `lts-10.10`. Does that resolve your issue?

**Comment by YotaVGA** [comment] 2018-03-18 15:15
cabal-install is suggested from stack solver, it doesn't work at all without it, IHaskell install perfectly and works, and lts-10.10 gives the similar errors:

```
Downloaded lts-10.10 build plan.    
Using configuration file: stack.yaml
The following packages are missing from the config:
- ihaskell-display/ihaskell-rlangqq/

Using cabal packages:
- ghc-parser/
- ./
- ihaskell-display/ihaskell-aeson/
- ihaskell-display/ihaskell-blaze/
- ihaskell-display/ihaskell-charts/
- ihaskell-display/ihaskell-diagrams/
- ihaskell-display/ihaskell-gnuplot/
- ihaskell-display/ihaskell-hatex/
- ihaskell-display/ihaskell-juicypixels/
- ihaskell-display/ihaskell-magic/
- ihaskell-display/ihaskell-plot/
- ihaskell-display/ihaskell-static-canvas/
- ihaskell-display/ihaskell-widgets/
- ipython-kernel/

Using resolver: lts-10.10

Warning: Installed version of cabal-install (2.0.0.0) is newer than stack has been tested with.  If you run into difficulties, consider downgrading.
         
Using compiler: ghc-8.2.2
Asking cabal to calculate a build plan...
Trying with packages from lts-10.10 and 16 external packages as hard constraints...
Attempt failed.

>>>> Cabal errors begin
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:240:21 in main:Distribution.Client.Install
cabal: Could not resolve dependencies:
trying: base-4.10.1.0/installed-4.1... (dependency of ghc-parser-0.2.0.2)
trying: ihaskell-static-canvas-0.1.0.0 (user goal)
next goal: static-canvas (dependency of ihaskell-static-canvas-0.1.0.0)
rejecting: static-canvas-0.2.0.3 (conflict: base==4.10.1.0/installed-4.1...,
static-canvas => base>=4.5 && <4.10)
rejecting: static-canvas-0.2.0.2, static-canvas-0.2.0.1,
static-canvas-0.2.0.0, static-canvas-0.1.0.0 (constraint from main config
/tmp/cabal-solver21418/cabal.config requires ==0.2.0.3)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base (30), ghc-parser (13),
static-canvas (6), ihaskell-static-canvas (2)
<<<< Cabal errors end

Retrying with packages from lts-10.10 and 16 external packages as preferences...
Attempt failed.

>>>> Cabal errors begin
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:240:21 in main:Distribution.Client.Install
cabal: Could not resolve dependencies:
trying: base-4.10.1.0/installed-4.1... (dependency of ghc-parser-0.2.0.2)
trying: ihaskell-static-canvas-0.1.0.0 (user goal)
next goal: static-canvas (dependency of ihaskell-static-canvas-0.1.0.0)
rejecting: static-canvas-0.2.0.3 (conflict: base==4.10.1.0/installed-4.1...,
static-canvas => base>=4.5 && <4.10)
rejecting: static-canvas-0.2.0.2, static-canvas-0.2.0.1,
static-canvas-0.2.0.0, static-canvas-0.1.0.0 (conflict:
base==4.10.1.0/installed-4.1..., static-canvas => base>=4.5 && <4.9)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base (34), ghc-parser (13),
static-canvas (6), ihaskell-static-canvas (2)
<<<< Cabal errors end

*** Failed to arrive at a workable build plan.

Solver could not resolve package dependencies.
You can try the following:
    - Update external packages with 'stack update' and try again.
    - Tweak stack.yaml and try again
        - Remove any unnecessary packages.
        - Add any missing remote packages.
        - Add extra dependencies to guide solver.
        - Adjust resolver.
```

**Comment by vaibhavsagar** [comment] 2018-03-18 15:19
This error is because of restrictive upper bounds in `static-canvas`. Try commenting it out in `extra-deps` and also commenting out `ihaskell-display/ihaskell-static-canvas` under `packages`.

**Comment by YotaVGA** [comment] 2018-03-18 16:50
Ok, it worked perfectly, thanks!

**Comment by vaibhavsagar** [comment] 2018-03-19 01:11
Wonderful, glad I could help!

**Closed** 2018-03-22 00:11 UTC
