### ISSUE TITLE
hspec tests fail

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#358] opened 2015-02-17 00:08 UTC
Trying to run cabal test on the current c324d1a (after including TH in the Cabal file) gives:

Failures:

  1) Code Evaluation evaluates expressions
       uncaught exception: ErrorCall (Expecting value!)

  2) Code Evaluation evaluates multiline expressions
       uncaught exception: ErrorCall (Expecting value!)

  3) Code Evaluation evaluates function declarations silently
       uncaught exception: ErrorCall (Expecting value!)

  4) Code Evaluation evaluates data declarations
       uncaught exception: ErrorCall (Expecting value!)

  5) Code Evaluation evaluates do blocks in expressions
       uncaught exception: ErrorCall (Expecting value!)

  6) Code Evaluation is silent for imports
       uncaught exception: ErrorCall (Expecting value!)

  7) Code Evaluation evaluates directives
       uncaught exception: ErrorCall (Expecting value!)

**Comment by gibiansky** [comment] 2015-02-17 00:11
Yeah, I know :( Duplicate of #272 to some extent. Not sure why it fails...

**Comment by houshuang** [comment] 2015-02-19 22:48
So I tried to figure out why the tests were failing, and what to do with it. Not very familiar with HSpec, but it turns out there are three different issues.

First, there seems to be a difference in running the tests with cabal test, defined under Test-Suite, and running the file as an executable. When I copy HSpec.hs to another file, and define it as an executable, and run it with cabal run, I get a colorized output, and fewer failing tests. 

Now we actually see what the failing tests are. Two tests are failing because of encoding issue.

The third test is an actual error. Somehow when auto-deriving, only the first item is picked up. Ie. if `derive(Show, Eq)`, it can show, but not compare. If `derive (Eq, Show)`, it's the opposite. I'm not quite sure where in the process this error happens, but it does check the items, because `derive (Eq, Stian)` tells me that it cannot derive Stian, so it doesn't just discard the items past the first...

![screen shot 2015-02-19 at 17 44 41](https://cloud.githubusercontent.com/assets/61575/6277721/1bff8322-b85f-11e4-90f3-34548c34c64e.png)

![screen shot 2015-02-19 at 17 47 31](https://cloud.githubusercontent.com/assets/61575/6277744/6c170cf4-b85f-11e4-9131-414879f25d1f.png)

**Comment by gibiansky** [comment] 2015-03-03 19:59
I'm still getting errors like these:
```
  7) Code Evaluation evaluates directives
       uncaught exception: ErrorCall (Expecting value!)
```
Did you find out why these were happening, or is that only happening for me?

**Comment by houshuang** [comment] 2015-03-03 20:05
As you see in my comment, that happens when you run it with cabal test, but
if you make it into an executable and just run it as an executable, you get
the actual output. No idea why!

On Tue, Mar 3, 2015 at 2:59 PM, Andrew Gibiansky <notifications@github.com>
wrote:

> I'm still getting errors like these:
>
>   7) Code Evaluation evaluates directives
>        uncaught exception: ErrorCall (Expecting value!)
>
> Did you find out why these were happening, or is that only happening for
> me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/358#issuecomment-77022193>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by gibiansky** [comment] 2015-03-03 20:09
Strange. I switched the test suite to produce an `ihaskell-tests` executable, then ran that executable, and got the same result. I'd figured you did something else to get it to work. Ugh. Will investigate more.

**Comment by houshuang** [comment] 2015-03-03 20:54
There is something weird with cabal test, every tutorial I found
recommended just runhaskell'ing the HSpec file directly. That works as long
as I remove the one CPP definition.

```haskell
15:51 IHaskell hspec* ❯ runhaskell src/Hspec.hs

src/Hspec.hs:34:1: Warning:
    Module ‘Test.Hspec.HUnit’ is deprecated:
      use "Test.Hspec.Contrib.HUnit" from package @hspec-contrib@ instead

Layout Chunk
  chunks 'a string'
  chunks 'a\n string'
  chunks 'a\n string\nextra'
  chunks strings with too many lines
  parses multiple exprs
Get Module Name
  parses simple module names
  parses module names with dots
  parses module names with exports
  errors when given unnamed modules
```

On Tue, Mar 3, 2015 at 3:09 PM, Andrew Gibiansky <notifications@github.com>
wrote:

> Strange. I switched the test suite to produce an ihaskell-tests
> executable, then ran that executable, and got the same result. I'd figured
> you did something else to get it to work. Ugh. Will investigate more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/358#issuecomment-77023998>.
>



-- 
http://reganmian.net/blog -- Random Stuff that Matters

**Comment by houshuang** [comment] 2015-03-03 20:55
There is something weird with cabal test, every tutorial I found
recommended just runhaskell'ing the HSpec file directly. That works as long
as I remove the one CPP definition.

```haskell
15:51 IHaskell hspec* ❯ runhaskell src/Hspec.hs

src/Hspec.hs:34:1: Warning:
    Module ‘Test.Hspec.HUnit’ is deprecated:
      use "Test.Hspec.Contrib.HUnit" from package @hspec-contrib@ instead

Layout Chunk
  chunks 'a string'
  chunks 'a\n string'
  chunks 'a\n string\nextra'
  chunks strings with too many lines
  parses multiple exprs
Get Module Name
  parses simple module names
  parses module names with dots
  parses module names with exports
  errors when given unnamed modules
```

**Comment by gibiansky** [comment] 2015-03-03 21:13
Strange! I've also just managed to get them to compile and run like that. I don't know what's going on, but perhaps it has to do with
```
src/Hspec.hs:34:1: Warning:
    Module ‘Test.Hspec.HUnit’ is deprecated:
      use "Test.Hspec.Contrib.HUnit" from package @hspec-contrib@ instead
```

In the short run, I will probably remove the test suite from `ihaskell.cabal`.

Thanks for digging into this a bit.

**Closed** 2015-03-05 21:52 UTC
