### ISSUE TITLE
ihaskell install fails on jupyter 4.5.0 with "Detected Jupyter, but could not parse version number."

### ISSUE THREAD

**Issue by essandess** [gibiansky/IHaskell#1058] opened 2019-06-27 23:23 UTC
I'm trying to create a MacPorts port of IHaskell. See https://github.com/macports/macports-ports/pull/4706

I get a full build up to the point of `jupyter --version`, then get the error message:
```
Detected Jupyter, but could not parse version number.
```

My `jupyter --version` returns:
```
jupyter core     : 4.5.0
jupyter-notebook : 5.7.8
qtconsole        : 4.5.1
ipython          : 7.5.0
ipykernel        : 5.1.1
jupyter client   : 5.2.4
jupyter lab      : not installed
nbconvert        : 5.5.0
ipywidgets       : 7.4.2
nbformat         : 4.4.0
traitlets        : 4.3.2
```

It looks like [requirements.txt](https://github.com/gibiansky/IHaskell/blob/master/requirements.txt) wants `4.4.0` for jupyter core, but there's a later version now.

Is this the issue?

If so, would it be possible to update to allow version `4.5.0`?

**Comment by vaibhavsagar** [comment] 2019-06-28 15:24
This has been addressed by ac478079dcbd6f947bac34bf190ad2f9d1e6891d, please try again and reopen if the issue is not yet fixed.

**Closed by vaibhavsagar** 2019-06-28 15:24 UTC

**Comment by essandess** [comment] 2019-06-28 21:32
Thanks you! That worked! But a new issue…

**Comment by vaibhavsagar** [comment] 2019-06-28 21:48
Oh, what is it?
