### ISSUE TITLE
using http-client-tls with ihaskell installed from stack causes a kernel restart

### ISSUE THREAD

**Issue by karshan** [gibiansky/IHaskell#741] opened 2017-08-28 22:58 UTC
Running the following snippet in ihaskell will cause an ihaskell kernel restart (presumably because of a crash). This snippet works correctly if compiled with ghc, or run in ghci.

Enabling debug messages via `ihaskell install --debug` doesn't provide any further information, jupyter just prints the following:
`WARNING:root:kernel 81b09e31-0145-4403-bf09-c5d2667afba5 restarted`

Tested on [f39b812fdcc5566210f9960f8218c5fc7fd40a77](https://github.com/gibiansky/IHaskell/commit/f39b812fdcc5566210f9960f8218c5fc7fd40a77)

dependencies: `http-client-0.5.7.0, http-client-tls-0.3.5.1`

snippet:
```
import Network.HTTP.Client
import Network.HTTP.Client.TLS

doGet = do
  manager <- newManager tlsManagerSettings

  request <- parseRequest "https://httpbin.org/ip"
  httpLbs request manager
doGet
```
If you use http instead of https, i.e. `"http://httpbin.org/ip"` the code executes correctly without a kernel restart.

Is there some way I can get more debugging information about why the kernel was restarted ?

**Comment by vaibhavsagar** [comment] 2017-08-29 22:03
Hi, thanks for providing a small reproduction! I don't know of a way to get more debugging information without making changes to the source code, but I will investigate further and see if I can find anything.

**Comment by vaibhavsagar** [comment] 2017-09-01 18:37
Hi, this seems to be working fine for me using a Nix-built environment from `master`, which includes its own `http-tls`: 
![ihaskell-http-tls](https://user-images.githubusercontent.com/1525767/29983203-5d8dff74-8f87-11e7-98ad-304b948ce541.png)

Can you tell me more about the setup you're using: Stack or Cabal, which revision, which extra packages, etc.?

**Comment by karshan** [comment] 2017-09-01 20:26
I'm using stack lts-9.2, I just tried with IHaskell installed from `master` and was able to reproduce the kernel restart. I have this in my stack config.yaml:
```
apply-ghc-options: everything
ghc-options:
  "*": -opta-Wa,-mrelax-relocations=no
```

and no extra packages in my stack.yaml:
```
packages:
- /home/karshan/gits/IHaskell/
- /home/karshan/gits/IHaskell/ipython-kernel
- /home/karshan/gits/IHaskell/ghc-parser
resolver: lts-9.2
```

**Comment by vaibhavsagar** [comment] 2017-09-02 01:52
That is strange! I don't have access to a stack-installed IHaskell for a few more days but I will continue investigating. Let me also bump the IHaskell resolver to `lts-9.2` and see if that makes any difference. What does your `.cabal` file look like?

**Comment by vaibhavsagar** [comment] 2017-09-09 05:54
I tried this and got this output on the console:

```
ihaskell: /home/vaibhavsagar/.stack/snapshots/x86_64-linux/lts-9.0/8.0.2/lib/x86_64-linux-ghc-8.0.2/cryptonite-0.23-EXqej153fRK6r6DVzkvS8x/libHScryptonite-0.23-EXqej153fRK6r6DVzkvS8x.a: unhandled ELF relocation(RelA) type 42

ihaskell: Could not on-demand load symbol 'cryptonite_aes_gen_ctr_cont'

ihaskell: /home/vaibhavsagar/.stack/snapshots/x86_64-linux/lts-9.0/8.0.2/lib/x86_64-linux-ghc-8.0.2/cryptonite-0.23-EXqej153fRK6r6DVzkvS8x/libHScryptonite-0.23-EXqej153fRK6r6DVzkvS8x.a: unknown symbol `cryptonite_aes_gen_ctr_cont'
ihaskell: Could not on-demand load symbol 'cryptonitezm0zi23zmEXqej153fRK6r6DVzzkvS8x_CryptoziCipherziAESziPrimitive_decryptCBC_closure'

ihaskell: /home/vaibhavsagar/.stack/snapshots/x86_64-linux/lts-9.0/8.0.2/lib/x86_64-linux-ghc-8.0.2/cryptonite-0.23-EXqej153fRK6r6DVzkvS8x/libHScryptonite-0.23-EXqej153fRK6r6DVzkvS8x.a: unknown symbol `cryptonitezm0zi23zmEXqej153fRK6r6DVzzkvS8x_CryptoziCipherziAESziPrimitive_decryptCBC_closure'
ihaskell: Could not on-demand load symbol 'cryptonitezm0zi23zmEXqej153fRK6r6DVzzkvS8x_CryptoziCipherziAES_zdfCipherAES128zuzdccipherInit_info'

ihaskell: /home/vaibhavsagar/.stack/snapshots/x86_64-linux/lts-9.2/8.0.2/lib/x86_64-linux-ghc-8.0.2/tls-1.3.11-CeqEoaiesLBCdJI0iTemNv/libHStls-1.3.11-CeqEoaiesLBCdJI0iTemNv.a: unknown symbol `cryptonitezm0zi23zmEXqej153fRK6r6DVzzkvS8x_CryptoziCipherziAES_zdfCipherAES128zuzdccipherInit_info'
ihaskell: Could not on-demand load symbol 'tlszm1zi3zi11zmCeqEoaiesLBCdJI0iTemNv_NetworkziTLSziExtraziCipher_ciphersuitezuall_closure'

ihaskell: /home/vaibhavsagar/.stack/snapshots/x86_64-linux/lts-9.2/8.0.2/lib/x86_64-linux-ghc-8.0.2/connection-0.2.8-FG6EhcQHxCe58OAp65GxNR/libHSconnection-0.2.8-FG6EhcQHxCe58OAp65GxNR.a: unknown symbol `tlszm1zi3zi11zmCeqEoaiesLBCdJI0iTemNv_NetworkziTLSziExtraziCipher_ciphersuitezuall_closure'
ihaskell: Could not on-demand load symbol 'connectionzm0zi2zi8zmFG6EhcQHxCe58OAp65GxNR_NetworkziConnection_zdfExceptionHostCannotConnect3_closure'

ihaskell: /home/vaibhavsagar/.stack/snapshots/x86_64-linux/lts-9.2/8.0.2/lib/x86_64-linux-ghc-8.0.2/http-client-tls-0.3.5.1-7D7AoXn5mijJjll6i1AypO/libHShttp-client-tls-0.3.5.1-7D7AoXn5mijJjll6i1AypO.a: unknown symbol `connectionzm0zi2zi8zmFG6EhcQHxCe58OAp65GxNR_NetworkziConnection_zdfExceptionHostCannotConnect3_closure'
ihaskell: Could not on-demand load symbol 'httpzmclientzmtlszm0zi3zi5zi1zm7D7AoXn5mijJjll6i1AypO_NetworkziHTTPziClientziTLS_tlsManagerSettings_closure'
```
but my `config.yaml` doesn't have the `ghc-options` you have. I've seen this issue before in https://github.com/gibiansky/IHaskell/issues/636#issuecomment-228571480, let me try unregistering `cryptonite` as indicated and building again.

**Comment by vaibhavsagar** [comment] 2017-09-09 06:06
Okay, now I'm seeing the same error as you are, with the kernel restarting and no other output.

**Comment by ErikCupal** [comment] 2017-12-13 00:28
also getting `ihaskell: Could not on-demand load symbol 'cryptonite_aes_gen_ctr_cont'` error on ubuntu, with lts 9.1 when I try do basic wreq get request :(. Any suggestions on how to fix this (e.g. which stack lts could work)?

**Comment by vaibhavsagar** [comment] 2017-12-13 02:20
I don't think there is an LTS that would work. If you can, try using the Nix approach, which doesn't seem to have this issue.

**Comment by ErikCupal** [comment] 2017-12-15 01:06
Thanks for suggestion @vaibhavsagar. I tried using stack with nix but `stack build` fails because of missing C libraries - [question on stackoverflow](https://stackoverflow.com/questions/47823825/missing-c-library-error-during-stack-build-with-nix).

I'm using nix for first time, so I'm probably just doing some silly mistake.

**Comment by vaibhavsagar** [comment] 2017-12-15 02:55
I was referring to using `nix-build release.nix` as described [here](https://github.com/gibiansky/IHaskell#nix), not Stack with Nix. Let's continue this on StackOverflow.

**Comment by vaibhavsagar** [comment] 2018-11-23 23:07
Closing, please reopen if needed.

**Closed by vaibhavsagar** 2018-11-23 23:07 UTC
