### ISSUE TITLE
IPython 4.0 support not on Hackage

### ISSUE THREAD

**Issue by orome** [gibiansky/IHaskell#556] opened 2015-08-18 14:11 UTC
When I follow the instructions and attempt to

    ihaskell install

[I get](http://stackoverflow.com/q/32074595/656912)

    Detected IPython, but could not parse version number.
    ihaskell: 
    Ran commands: 
    which ipython
    /usr/local/bin/ipython --version
    which /usr/local/bin/ipython

    Exception: ExitFailure 1

which makes no sense since the instructions say (or seem to me to say) that anything my current version of IPython (4.0.0 as reported by `/usr/local/bin/ipython --version`) is supported.

[How can I proceed?](http://stackoverflow.com/q/32074595/656912)

**Comment by orome** [comment] 2015-08-18 14:16
From #553, it looks like (say it isn't so) the current version of IPython is not supported! I'm not sure what to do (the documentation didn't mention this). 

Will there be an update released soon? I'm not a developer and am not installing from source but will be using version available through Cabal.

**Comment by gibiansky** [comment] 2015-08-18 14:16
We're still working out issues with jupyter 4.0. It may work if you install from github master. (I say may because it works for me but not everyone...)

(Where does it say ipython 4.0 is supported? Trying to make that happen ASAP but not yet officially true... )

What commit did you install?

**Comment by gibiansky** [comment] 2015-08-18 14:20
IPython 4 was released only a few days ago :) so still trying to get stuff fixed for it. One man show here where the man was on vacation last week :)

Either install from source on github, install ipython 3 instead of 4 (recommended), or wait a few days (also recommended).

Installing an older version of ipytgon should be fairly easy, so I would go that route

**Comment by orome** [comment] 2015-08-18 14:20
I installed through Cabal. 

The docs [say](https://github.com/gibiansky/IHaskell/blob/master/README.md#install-ipython) to "Install IPython 3.0 or above" and then give instructions to execute

    pip install ipython[all]

which installs 4.0.0.

Backing out to a different version or installing from source is not something I'm prepared to do, so I may have to wait. Any idea how long that will be?

**Comment by gibiansky** [comment] 2015-08-18 14:27
I expect it will be a few days (a week at most). It is a high priority.

FYI using IPython 3.0 is fairly easy and I'm happy to help you downgrade for the time being if you would like. The three commands you need to run are
```bash
pip uninstall ipython
pip uninstall jupyter_core
pip install ipython[notebook]==3.0
```
(if you are on Mac you will need to put `sudo` in front of it)

After that you can verify that you are using IPython 3 by running `ipython --version` and getting `3.0.0`, and running `jupyter --version` and getting a "command not found" error

**Comment by orome** [comment] 2015-08-18 14:31
Thanks! I think I'll wait (or maybe I'll give that a try if I get impatient). I look forward to the update.

I assume I'll know an update has been pushed when this closes. How long after that for it to appear as the Cabal version?

And: If I do back out to 3.0, what do I need to do to get back to the current IPython, just `pip install ipython[notebook]`?

**Comment by gibiansky** [comment] 2015-08-18 14:33
I'll close this once a new version has been uploaded to Hackage.

If you back down to 3.0, and then want to get back to 4.0, just run
```bash
pip install ipython[notebook] --upgrade
```

(FYI by downgrading to 3.0 you will lose almost nothing. The user interface and experience and feature list between the two versions is incredibly similar. Unless you are a heavy user of IPython you would not be able to tell the difference at all, I think.)

**Comment by orome** [comment] 2015-08-18 14:37
Cool, thanks!

**Comment by orome** [comment] 2015-08-18 14:49
3.0 seems to work! I look forward to the update!

----

BTW FWIW, I had established a path to `ihaskell` by putting

    ~/Library/Haskell/bin

in `/privat/etc/paths`, which worked at the prompt but caused `ihaskell install` to fail with

    Exception: ihaskell not on $PATH and not referenced relative to directory.

Replacing `~` with `/Users/Rax` solved the problem.

I'm not sure if that's an IHaskell issue or just a general property of paths in the OS.

**Comment by duetosymmetry** [comment] 2015-08-19 04:06
BTW, on Mac OS X: the script `macos-install.sh` includes the command

        pip install -U 'ipython[all]'

Therefore, even if somebody had ipython 4, and backs out to ipython 3, running `macos-install.sh` will re-upgrade them to version 4, and the build will fail.

**Comment by orome** [comment] 2015-08-19 10:53
@duetosymmetry: Does that have any implications for the instructions @gibiansky gave? Can you elaborate? (Remember, I'm just using the basic "consumer" install, not dev builds.)

**Comment by duetosymmetry** [comment] 2015-08-21 20:15
@orome there is no problem doing `ihaskell install` by hand.

**Comment by gibiansky** [comment] 2015-08-23 04:31
Support should now be on Hackage. Let me know if there are more problems. They may still exist – it works for me but definitely needs more testing.

**Closed by gibiansky** 2015-08-23 04:31 UTC

**Comment by orome** [comment] 2015-08-23 11:28
@gibiansky I've gone back to 4.0 as instructed above (`pip install ipython[notebook] --upgrade` followed by `ihaskell install`) and things seem to work well. The only differences I see are that on launching or creating a new notebook I get

    Unimplemented message: CommOpen {header = MessageHeader {identifiers = ["88E40EE20B544E6E9C7CA12D7FF0A8F2"], parentHeader = Nothing, metadata = fromList [], messageId = UUID {uuidToString = "8FD3CBF8845145B8A09DF415A9DA83BD"}, sessionId = UUID {uuidToString = "88E40EE20B544E6E9C7CA12D7FF0A8F2"}, username = "username", msgType = CommOpenMessage}, commTargetName = "ipython.widget", commUuid = UUID {uuidToString = "5A9C56D29BA4451A9AF7B28CCF8346DA"}, commData = Object (fromList [("widget_class",String "ipywidgets.CommInfo")])}

and the warning

    404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js (::1) 8.25ms referer=http://localhost:8888/notebooks/Haskell/NotebookName.ipynb

not necessarily in that order.

**Comment by orome** [comment] 2015-08-23 16:15
@gibiansky And there's a big problem with formatting (not present in the previous version): #560.

**Comment by gibiansky** [comment] 2015-08-23 16:16
The messages are expected. I don't know why IPython 4.0 sends them, though. I have a guess as to the cause of the formatting issues, will look into it. Thanks for filing issues.

**Comment by orome** [comment] 2015-08-23 16:25
Thanks. 

(BTW, how do I display the IHaskell version being used by Jupyter? Is there a way to do that from within a notebook?)
