### ISSUE TITLE
import IHaskell.Display does not work with stack?

### ISSUE THREAD

**Issue by habbler** [gibiansky/IHaskell#1312] opened 2022-01-06 22:15 UTC
Hello,

How do I make IHaskell.Display available when starting Jupyter in the directory of my stack projects?

When I execute "import IHaskell.Display" I get the error that it is not found.
When I do :set -v, it looks like it is searching for a directly IHaskell in my current project directory.
I tried adding it ihaskell to the packages or extra-deps sections of my stack.yaml file of my project.
This did not work either. Under packages it again looks for a IHaskell directory in my current project.
extra-deps packages to not seem to be available in IHaskell.

Does IHaskell execute "stack ghci" somewhere? I see that there is an option -packages to add extra packages to the stack ghci exectution?

Best regards,

**Comment by vaibhavsagar** [comment] 2022-01-07 07:17
After you added `ihaskell` to `packages`, did you run `stack install`? https://github.com/gibiansky/IHaskell#where-are-my-packages-ihaskell--stack

**Comment by habbler** [comment] 2022-01-07 09:32
Hi,

I just tried running stack install on my own project. This made no difference as I expect.

I think the above are instructions for make extra packages (excluding IHaskell) available when using IHaskell.

In my case the problem more seems to be that the IHaskell package itself is not available within the IHaskell interpreter.

I suspect also that perhaps the instructions above are old? Most of the functionality of packages in stack was moved to extra-deps. But these extra deps to not seem to be available with ghci.

Best regards.

**Comment by vaibhavsagar** [comment] 2022-01-08 21:05
> I think the above are instructions for make extra packages (excluding IHaskell) available when using IHaskell

The instructions work the same for IHaskell as every other package.

> In my case the problem more seems to be that the IHaskell package itself is not available within the IHaskell interpreter.

That's by design, but it can be included if desired. Let's try something different: can you add `ihaskell` to the `.cabal` (or `package.yaml`) file of your project and build? It should then be available when using IHaskell (try `:! stack exec -- ghc-pkg list` to confirm this).

**Comment by habbler** [comment] 2022-01-10 20:52
I add a dependency to ihaskell in my .cabal file, and added 
extra-deps:
- ihaskell-0.10.2.2
in the stack.yaml file.
However when I attempt to stack build my project I get the following error.

ihaskell     > configure
ihaskell     > Configuring ihaskell-0.10.2.2...
ihaskell     > build
ihaskell     > Preprocessing library for ihaskell-0.10.2.2..
ihaskell     > Building library for ihaskell-0.10.2.2..
ihaskell     > [ 1 of 25] Compiling IHaskellPrelude
ihaskell     > [ 2 of 25] Compiling IHaskell.Types
ihaskell     >
ihaskell     > /tmp/stack-e445d1e091c77320/ihaskell-0.10.2.2/src/IHaskell/Types.hs:165:36: error:
ihaskell     >     Variable not in scope:
ihaskell     >       displayDataToJson
ihaskell     >         :: DisplayData -> aeson-1.5.6.0:Data.Aeson.Types.Internal.Pair
ihaskell     >     |
ihaskell     > 165 |   toJSON (Display d) = object (map displayDataToJson d)
ihaskell     >     |                                    ^^^^^^^^^^^^^^^^^
ihaskell     >

Not sure why. When I build IHaskell in the IHaskell directory it works.

You say above "That's by design, but it can be included if desired.". How would I do that?

Best regards,

**Comment by vaibhavsagar** [comment] 2022-01-10 22:25
That's what we're trying to figure out :smile:. The way IHaskell works outside a Haskell project directory is that it only loads GHC boot packages (e.g. `bytestring`, `text`, `array`, `binary`, etc.), but inside a Haskell project directory we have a couple of different approaches to picking up the dependencies of the project, so that IHaskell can be used somewhat like GHCi (although it behaves differently in many ways). That's why we're trying to include `ihaskell` as a dependency of your Stack project, so that the existing logic we have to pick up dependencies will also work with `ihaskell` (which as I mentioned above, is the same as any other dependency).

I don't really use Stack much so I'm not the best person to ask about debugging your build issues, but maybe if you are able to share your project I can look further? I think your issue might be that you also need to include `ipython-kernel`, since that is where `displayDataToJson` is defined.

**Comment by habbler** [comment] 2022-01-11 20:38
Hi,

Thanks for the help.

You tip of adding ipython-kernel to my extra-deps fixed the build error. Though I think this should not be necessary.
The ihaskell package already has a dependency on the ipython-kernel package.

I can also then use IHaskell.Display in my Jupyter session!

So in some ways this is a solution...
But not one I am so keen on. It increase the build time as it pulls in the  ihaskell package and dependencies. I also need to modify my stack.yaml and cabal files of my package.

The stack ghci command has the -package option to add an extra package to the ghci session.
If I feel motivated I might take a look at how this is implemented. Maybe the same technique can be used to make the ihaskell package available in the IHaskell kernel.

Best regards,

**Comment by vaibhavsagar** [comment] 2022-01-12 05:46
>You tip of adding ipython-kernel to my extra-deps fixed the build error. Though I think this should not be necessary.

I agree, unfortunately this is a limitation of Stack and not something I am able to fix on my end.

> It increase the build time as it pulls in the ihaskell package and dependencies. I also need to modify my stack.yaml and cabal files of my package.

I think it makes sense that if you want a package to be available in your development environment it should be included as a dependency.

> The stack ghci command has the -package option to add an extra package to the ghci session.
If I feel motivated I might take a look at how this is implemented. Maybe the same technique can be used to make the ihaskell package available in the IHaskell kernel.
>
> I guess another option would be for class IHaskellDisplay and helper functions to be in an own mini package ihaskell-display which could be included in other packages without adding much overhead.

As it happens there are already issues for both these changes, https://github.com/gibiansky/IHaskell/issues/1210 and https://github.com/gibiansky/IHaskell/issues/1293. I'm going to go ahead and close this since your issue is resolved.

**Closed by vaibhavsagar** 2022-01-12 05:46 UTC
