### ISSUE TITLE
Nix build fails

### ISSUE THREAD

**Issue by stschiff** [gibiansky/IHaskell#770] opened 2017-10-21 21:38 UTC
Hi, I am running Nix on Mac OS X High Sierra in Single User mode, and after many other lines, get an error (see attached output). Any clues? Can you reproduce this on High Sierra? Thanks!

    Hunk #1 FAILED at 24.
    1 out of 1 hunk FAILED -- saving rejects to file mkspecs/features/mac/default_post.prf.rej
    patching file mkspecs/features/mac/default_pre.prf
    Reversed (or previously applied) patch detected!  Assume -R? [n]
    Apply anyway? [n]
    Skipping patch.
    1 out of 1 hunk ignored -- saving rejects to file mkspecs/features/mac/default_pre.prf.rej
    patching file mkspecs/features/mac/sdk.prf
    Reversed (or previously applied) patch detected!  Assume -R? [n]
    Apply anyway? [n]
    Skipping patch.
    1 out of 1 hunk ignored -- saving rejects to file mkspecs/features/mac/sdk.prf.rej
    builder for ‘/nix/store/22f5iaypjqq592l5fpc1hjm3ddnvjji8-qtbase-5.9.2.drv’ failed with exit code 1
    cannot build derivation ‘/nix/store/pc6b9ni2c4x0dkr74ijyaawl3llmljhy-python3.6-PyQt-5.9.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/a3hqwvy6hn3h8s14avgrbrb17x3mz10l-python3-3.6.2-env.drv’: 1 dependencies couldn't be built
    killing process 6540
    killing process 6541
    cannot build derivation ‘/nix/store/i0yb1b9pzbjd8gsh5fl19sr6b0ijgvbj-ihaskell-with-packages.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/i0yb1b9pzbjd8gsh5fl19sr6b0ijgvbj-ihaskell-with-packages.drv’ failed

**Comment by vaibhavsagar** [comment] 2017-10-22 01:05
Hi, thanks for raising this! It looks like a [build error with one of the Qt dependencies](https://github.com/NixOS/nixpkgs/issues/27474). I unfortunately don't have a macOS machine to test with so I don't know when this breaks, but I'm thinking about setting up Travis builds as a first step to resolving the issue.

**Comment by Eoksni** [comment] 2018-01-13 16:18
I have a different issue with Nix build - it doesn't even start.
```
$ nix-build release.nix --arg packages "haskellPackages: [ haskellPackages.lens ]"

error: attribute ‘callCabal2nix’ missing, at /home/vagrant/src/IHaskell/release.nix:41:24
```

I use NixOS 16.09 as guest OS in VirtualBox.

**Comment by vaibhavsagar** [comment] 2018-01-13 17:39
@Eoksni that's because `callCabal2nix` is only available in `17.03` onwards and `ghc822` is only available in `17.09` onwards. You can use a newer `nixpkgs` in by e.g. saving the below to `default.nix` and calling `nix-build`:

```nix
let
  inherit (import <nixpkgs> {}) fetchFromGitHub;
  versions = {
    ihaskell = fetchFromGitHub {
      owner = "gibiansky";
      repo = "IHaskell";
      rev = "bf6759ed8e0a151d5cd190a0e00d107b607be68b";
      sha256 = "1cnydc5klqd8dzfj9npcq3wxw63pg9s847gqi4l7hs4w47q1mns4";
    };
    nixpkgs = fetchFromGitHub {
      owner = "NixOS";
      repo = "nixpkgs-channels";
      rev = "0653b73bf61f3a23d28c38ab7e9c69a318d433de";
      sha256 = "0s9m3g6nj7bflmrbhx8pcna6s8c9npn75p8ngyj5s8zbdaj7rs7l";
    };
  };
in import "${versions.ihaskell}/release.nix" {
  nixpkgs = import versions.nixpkgs {};
  packages = self: with self; [
    lens
  ];
}
```

**Comment by Eoksni** [comment] 2018-01-13 17:45
@vaibhavsagar thanks! I wonder where did you get that info because googleing for `callCabal2nix` gave me pretty much nothing.

**Comment by SFrijters** [comment] 2018-02-11 11:43
Probably not the same problem - and likely an upstream one - but nix-build is failing for me as well - can anyone reproduce this?

$ nix-build release-8.2.nix

[...]

Warning:
    This package indirectly depends on multiple versions of the same package. This is very likely to cause a compile failure.
      package haskell-src-meta (haskell-src-meta-0.8.0.2-HGDvi5Q5bazJbmGwUa2dRb) requires haskell-src-exts-1.19.1-GkJUFo8Rp3b1KlAdoTXU6c
      package ihaskell (ihaskell-0.9.0.2) requires haskell-src-exts-1.20.1-835K5nW7Qg0K3DUFrUYhiW
      package hlint (hlint-2.0.15-5X6UTbWTbxnHbrMIDeJ1Rx) requires haskell-src-exts-1.20.1-835K5nW7Qg0K3DUFrUYhiW
      package haskell-src-exts-util (haskell-src-exts-util-0.2.2-1qVFVzysPxYATIqV6LN4mV) requires haskell-src-exts-1.20.1-835K5nW7Qg0K3DUFrUYhiW

[...]

No pkg-config found
Using runghc version 8.2.2 found on system at:
/nix/store/g3gq089b9zyk7545vx9jn682wxmr6va2-ghc-8.2.2/bin/runghc
Using strip version 2.28 found on system at:
/nix/store/5qj61lcvzlap87rf6blvf8p577d482bv-binutils-2.28.1/bin/strip
Using tar found on system at:
/nix/store/1jn750iav5rfbm05345ysi8dvxcz7j26-gnutar-1.30/bin/tar
No uhc found
*** abort because of serious configure-time warning from Cabal
builder for ‘/nix/store/76h2s6drdbkgv8ci666jh05jq9qr6lzw-ihaskell-0.9.0.2.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/z6r6r7laaa59917czh0vhkh5jiz55dpd-ghc-8.2.2-with-packages.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/s5mlbj9mvj45ysq1zpl2gnh50gx7abvx-ihaskell-with-packages.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/s5mlbj9mvj45ysq1zpl2gnh50gx7abvx-ihaskell-with-packages.drv’ failed

**Comment by vaibhavsagar** [comment] 2018-02-11 13:45
I've had this happen when I have conflicting files in `~/.ghc`. Try doing a `rm -rf ~/.ghc` and running `nix-build` again.

**Comment by vaibhavsagar** [comment] 2018-02-11 13:45
Possibly `~/.cabal` in your case.

**Comment by SFrijters** [comment] 2018-02-11 14:01
Thanks, looked into this, but I didn't have a `~/.cabal` directory at all, and `~/.ghc` contained only my GHCi history file, so cleaning that didn't help. I don't have a system ghc installed at all either by the way.

**Comment by vaibhavsagar** [comment] 2018-02-11 14:11
Could it be that you are building with `nixpkgs-unstable`? [This override](https://github.com/NixOS/nixpkgs/blob/160d24087c942005aa64fbb22617f8320ef5bb40/pkgs/development/haskell-modules/configuration-common.nix#L611) might be causing your issue.

**Comment by SFrijters** [comment] 2018-02-11 14:32
I think I found the root cause of the issue: https://github.com/bmillwood/haskell-src-meta/blob/master/haskell-src-meta.cabal was updated recently with loosened upper version bounds on haskell-src-exts, but no release has been made, so the nix version still requires haskell-src-exts < 1.20. So it's an upstream issue - sorry for the noise.

**Comment by vaibhavsagar** [comment] 2018-02-11 15:27
No worries!

**Comment by vaibhavsagar** [comment] 2018-03-28 14:57
Closing this.

**Closed by vaibhavsagar** 2018-03-28 14:57 UTC
