### ISSUE TITLE
Kronos Haskell code cell output mangles Unicode

### ISSUE THREAD

**Issue by sacundim** [gibiansky/IHaskell#338] opened 2015-01-11 08:34 UTC
Putting the following into a code cell in Kronos Haskell:

    putStrLn "Español"
    putStrLn "人之初 性本善 性相近 習相遠"
    putStrLn $ "1 second/day ≈ " ++ show (1e6 / 86400) ++ " PPM"

...is producing the following output:

    EspaÃ±ol
    äººä¹å æ§æ¬å æ§ç¸è¿ ç¿ç¸é 
    1 second/day â 11.574074074074074 PPM

The .ipynb file looks like this:

    {
     "metadata": {
      "language": "haskell",
      "signature": "sha256:cc967b1380f2462bac7133d76c8b925997c4fcbe9d97d15d6eb4ff6660f22d06"
     },
     "nbformat": 3,
     "nbformat_minor": 0,
     "worksheets": [
      {
       "cells": [
        {
         "cell_type": "code",
         "collapsed": false,
         "input": [
          "putStrLn \"Espa\u00f1ol\"\n",
          "putStrLn \"\u4eba\u4e4b\u521d \u6027\u672c\u5584 \u6027\u76f8\u8fd1 \u7fd2\u76f8\u9060\"\n",
          "putStrLn $ \"1 second/day \u2248 \" ++ show (1e6 / 86400) ++ \" PPM\""
         ],
         "language": "python",
         "metadata": {},
         "outputs": [
          {
           "metadata": {},
           "output_type": "display_data",
           "text": [
            "Espa\u00c3\u00b1ol"
           ]
          },
          {
           "metadata": {},
           "output_type": "display_data",
           "text": [
            "\u00e4\u00ba\u00ba\u00e4\u00b9\u008b\u00e5\u0088\u009d \u00e6\u0080\u00a7\u00e6\u009c\u00ac\u00e5\u0096\u0084 \u00e6\u0080\u00a7\u00e7\u009b\u00b8\u00e8\u00bf\u0091 \u00e7\u00bf\u0092\u00e7\u009b\u00b8\u00e9\u0081\u00a0"
           ]
          },
          {
           "metadata": {},
           "output_type": "display_data",
           "text": [
            "1 second/day \u00e2\u0089\u0088 11.574074074074074 PPM"
           ]
          }
         ],
         "prompt_number": 2
        }
       ],
       "metadata": {}
      }
     ]
    }

**Comment by gibiansky** [comment] 2015-01-12 04:33
Thanks for reporting this – this is an issue with IHaskell. Will need to do some debugging to figure out what the issue is.

**Comment by gibiansky** [comment] 2015-08-29 20:15
This is a [known issue](https://github.com/gibiansky/IHaskell/issues/546) so I'm closing this as a duplicate.

**Closed by gibiansky** 2015-08-29 20:15 UTC
Labels: kronos
