### ISSUE TITLE
Display modules sometimes not loaded 

### ISSUE THREAD

**Issue by schernichkin** [gibiansky/IHaskell#737] opened 2017-08-02 19:07 UTC
I have cloned IHaskell from repo and installed it with following commands:
`stack solver && stack install`
`ihaskell install --stack`

Then I've started jupiter with:
`stack exec jupyter -- notebook`

After that I've opened ihaskell-display/ihaskell-diagrams/Test.ipynb and run all cells. The last one finished with error:
`<interactive>:1:1: error:`
`    • No instance for (Show (Renderable ())) arising from a use of ‘print’`
`    • In a stmt of an interactive GHCi command: print it`

Then I navigated to the notebooks folder, created new notebook and copied ihaskell-display/ihaskell-diagrams/Test.ipynb content with copy-paste in my browser. All cells run successfully and last one drew diagram just as excepted. I also can not import IHaskell.Display when using notebook from different folder, but in the notebooks/ it works fine.

**Comment by vaibhavsagar** [comment] 2017-08-03 00:55
Thanks for reporting this! I think it's a consequence of the way `stack` installs IHaskell. Closing as a duplicate of #715

**Closed by vaibhavsagar** 2017-08-03 00:55 UTC
