### ISSUE TITLE
The presence of rc.hs causes No Module Error outside IHaskell directory

### ISSUE THREAD

**Issue by konn** [gibiansky/IHaskell#843] opened 2018-03-22 06:44 UTC
If we want to run [`HaskellR`][HaskellR] on IHaskell, we need to pass `:set -fno-ghci-sandbox` flag to ghci and one easy solution is to add this line to `~/.ihaskell/rc.hs`, as stated in [HaskellR FAQ].

However, it seems that the presence of `rc.hs` causes the following odd module error and language kernel crash, if one launch `stack exec -- jupyter notebook` *OUTSIDE* the IHaskell directory; i.e. `git clone`'ed directory of IHaskell repo.

```ghci
[I 15:32:41.839 NotebookApp] Kernel started: 26193c48-5fa5-44ec-b8b3-31e2f1d47bf1
ihaskell: Not in scope: ‘IHaskell.Display.displayFromChanEncoded’
No module named ‘IHaskell.Display’ is imported.
```

If there is no `rc.hs`, this error doesn't occur.

[HaskellR]: https://tweag.github.io/HaskellR/
[HaskellR FAQ]: https://tweag.github.io/HaskellR/docs/faq.html#why-do-i-get-a-stack-limit-error-when-using-ghci-or-jupyter-and-how-can-i-fix-it

**Comment by konn** [comment] 2018-03-22 08:26
@vaibhavsagar It seems that there is no such file in my environment... Furthermore, it seems that there is no such directory named `~/.local/share/jupyter`

**Comment by vaibhavsagar** [comment] 2018-03-22 08:38
Maybe it's in a different directory. What's the output of `jupyter kernelspec list` and does that tell you the location of the IHaskell `kernel.json`?

**Comment by konn** [comment] 2018-03-22 08:40
I got it. It says:

```
Available kernels:
  haskell    /Users/hiromi/Library/Jupyter/kernels/haskell
  python3    /usr/local/share/jupyter/kernels/python3
```

and here is the content of `/Users/hiromi/Library/Jupyter/kernels/haskell/kernel.json` data in :

```json
{"display_name":"Haskell","argv":["/path/to/home/.local/bin/ihaskell","kernel","{connection_file}","--ghclib","/path/to/home/.stack/programs/x86_64-osx/ghc-8.2.2/lib/ghc-8.2.2","+RTS","-M3g","-N2","-RTS","--stack"],"language":"haskell"}
```

**Comment by vaibhavsagar** [comment] 2018-03-22 08:48
Thanks, let me try to reproduce this.

**Comment by vaibhavsagar** [comment] 2018-03-24 12:58
I can't seem to reproduce this yet on Linux. I've tried both `nix` and `stack` and both seem to handle `rc.hs` fine. Can I ask you to try reproducing this with a clean install of IHaskell on macOS? I unfortunately don't have a device running macOS to test myself so I'm really hoping this isn't a platform-specific bug.

**Comment by vaibhavsagar** [comment] 2018-05-07 14:49
Have you had the chance to take another look at this?

**Comment by konn** [comment] 2018-05-08 09:56
Oops, I overlooked your reply. Sorry.

Well, `nix-build release.nix` resulted in an error:

```
error: attribute 'haskell-src-exts_1_20_2' missing, at /Users/hiromi/Documents/Programming/Haskell/IHaskell/release.nix:50:25
```

I'm really new to nix and had never used so there might be some misoperation in setup, though.

**Comment by vaibhavsagar** [comment] 2018-05-08 10:34
Your Nix installation is different enough to mine to be causing problems :smile:. Can you try copying the following into a file called `notebook.nix` and running `nix-build notebook.nix`?

```nix
let
  fetcher = { owner, repo, rev, sha256 }: builtins.fetchTarball {
    inherit sha256;
    url = "https://github.com/${owner}/${repo}/archive/${rev}.tar.gz";
  };
  nixpkgs = fetcher {
    owner =  "NixOS";
    repo =  "nixpkgs-channels";
    rev =  "7cbf6ca1c84dfc917c1a99524e082fb677501844";
    sha256 =  "13rh31kj3j6ips3wpbqzcjjdvnhry05bf57l80z912ff2a3ma856";
  };
  ihaskell = fetcher {
    owner =  "gibiansky";
    repo =  "IHaskell";
    rev =  "39380616c10c9e698c393844767e55ec30ee3ba6";
    sha256 =  "1ync6lsh6vcjpsghf4w0mvz1nadxqjlh40nmnqqamzgw4awgvcba";
  };
in import "${ihaskell}/release.nix" {
  nixpkgs = import nixpkgs {};
  compiler = "ghc822";
}
```

**Comment by konn** [comment] 2018-05-08 13:53
It progressed, but it seems get stuck after the following line emitted:

```
warning: unable to download 'https://cache.nixos.org/nar/0xpm1d6i05mw4klyc7ghqr9lff0zkyf2bzdf3v90v9dcl1mcvf8c.nar.xz': HTTP error 200 (curl error: Stream error in the HTTP/2 framing layer); retrying in 330 ms
```

**Comment by vaibhavsagar** [comment] 2018-05-08 14:13
That means something failed to download. It's safe to cancel and retry.

**Comment by konn** [comment] 2018-05-10 08:07
After several times of recompilation, it finally fails to compile: 

```
builder for '/nix/store/ffja7pc88r4wyfk98pi9nk3yha9adblr-qtwebengine-5.10.1.drv' failed with exit code 1
cannot build derivation '/nix/store/bzzbb1hrm0dz3rvndyi3mbbxqvyv3mai-python3.6-PyQt-5.10.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/asds576kwc2x8zqprh598dvivhnna73b-python3-3.6.5-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6fb11znvvrprhcj24b0cb66mihhfml8v-ihaskell-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/6fb11znvvrprhcj24b0cb66mihhfml8v-ihaskell-with-packages.drv' failed
```

Here is [the complete log](https://gist.github.com/konn/66ec2e646e83ff2622d20981e20aadc9#file-nix-log-log).

**Comment by vaibhavsagar** [comment] 2018-05-10 09:49
That looks like https://github.com/NixOS/nixpkgs/issues/36932. It's frustrating that that doesn't work. I'm not sure how to proceed from here, maybe we can wait for that bug to get fixed upstream?

**Comment by vaibhavsagar** [comment] 2018-08-17 06:40
Building on macOS has been fixed, can you try again with the following `notebook.nix`?

```nix
let
  fetcher = { owner, repo, rev, sha256 }: builtins.fetchTarball {
    inherit sha256;
    url = "https://github.com/${owner}/${repo}/archive/${rev}.tar.gz";
  };
  nixpkgs = fetcher {
    owner =  "NixOS";
    repo =  "nixpkgs-channels";
    rev = "89ff9f94b67db63d18cc0707f8fd74d1244516fb";
    sha256 = "1x6zk7vrnnv236n3cws70jsaxmb2aibb8m32jbrfv2ni5rfq3dgn";
  };
  ihaskell = fetcher {
    owner =  "gibiansky";
    repo =  "IHaskell";
    rev =  "0d454acc4d7752ce16bf7f321f308f602f6555ea";
    sha256 =  "041v7zlgvwf5bbvi52n2cp4kld0x7lcdij2fss7076bxkc8k0ayy";
  };
in import "${ihaskell}/release.nix" {
  nixpkgs = import nixpkgs {};
  compiler = "ghc822";
}
```

**Comment by vaibhavsagar** [comment] 2018-11-14 19:18
Closing this, please reopen if necessary.

**Closed by vaibhavsagar** 2018-11-14 19:18 UTC
