### ISSUE TITLE
IHasell not finding some packages

### ISSUE THREAD

**Issue by orome** [gibiansky/IHaskell#581] opened 2015-10-01 17:32 UTC
I recently switched from using Haskell Plarform to using Homebrew for managing my Haskell installation. This change was without issues for GHCi but IHaskell is now unable to find many packages. For example  if I 

    import Data.List.Split 

I get

> Failed to load interface for ‘Data.List.Split’

even though the same import statement works fine in GHCi.

Is there something I can do to fix this? What would be causing IHaskell to be looking in the wrong location for installed packages?

---

FWIW, this occurred following an upgrade from OS X 10.10 to 10.11.

**Comment by gibiansky** [comment] 2015-10-01 18:25
I suggest reinstalling ihaskell, then rerunning ihaskell install.

Have you tried this?

**Comment by orome** [comment] 2015-10-01 18:31
Yes, several times. I went through the whole procedure (all the way from reinstalling IPython) and reinstalled everything.

**Comment by orome** [comment] 2015-10-01 18:34
Here's one possibility: IHaskell is only using one package db, rather than the full set. When I 

    ghc-pkg list

I see two package dbs:

    /usr/local/Cellar/ghc/7.10.2/lib/ghc-7.10.2/package.conf.d

and

    /Users/Rax/.ghc/x86_64-darwin-7.10.2/package.conf.d

GHC, GHCi, Cabal, and Stack all see both of these as they should, but IHaskell only seems to be able to import a package if it is in the first, and knows nothing about packages in the second.

**Comment by orome** [comment] 2015-10-02 12:14
To be pieces, I gather that it is my `user` packages that IHaskell is not seeing.

**Comment by gibiansky** [comment] 2015-10-02 15:53
So, you can see what IHaskell is using by looking at the `--ghc-lib` argument. If you run
```
jupyter --data-dir
```
it will print out a directory. In that directory there will be a file `kernels/haskell/kernel.json`. 

What does this file contain?

**Comment by orome** [comment] 2015-10-02 15:56
`{"display_name":"Haskell","argv":["/Users/Rax/.cabal/bin/ihaskell","kernel","{connection_file}","--ghclib","/usr/local/Cellar/ghc/7.10.2/lib/ghc-7.10.2"],"language":"haskell"}`

**Comment by orome** [comment] 2015-10-04 13:21
So is Jupyter the culprit? How do I configure it to use the the user packages as well as the global ones (and shouldn't it do that by default)?

**Comment by orome** [comment] 2015-10-04 13:25
Or do I need to run something like 

    ihaskell install -ghclib=<globalpath>:<userpath>

**Comment by sumitsahrawat** [comment] 2015-10-04 13:57
The easiest solution would be to switch to only one way of managing haskell packages. The different ways are not very inter-operable, e.g. packages installed using stack aren't visible to cabal, and vice versa.

`stack` should be the best option IMO.

**Comment by sumitsahrawat** [comment] 2015-10-04 14:07
The culprit in this case is this:

At https://github.com/gibiansky/IHaskell/blob/master/src/IHaskell/IPython.hs#L44-L58:

```haskell
data KernelSpecOptions =
       KernelSpecOptions
         { kernelSpecGhcLibdir :: String           -- ^ GHC libdir.
         , kernelSpecDebug :: Bool                 -- ^ Spew debugging output?
         , kernelSpecConfFile :: IO (Maybe String) -- ^ Filename of profile JSON file.
         , kernelSpecInstallPrefix :: Maybe String
         }

defaultKernelSpecOptions :: KernelSpecOptions
defaultKernelSpecOptions = KernelSpecOptions
  { kernelSpecGhcLibdir = GHC.Paths.libdir
  , kernelSpecDebug = False
  , kernelSpecConfFile = defaultConfFile
  , kernelSpecInstallPrefix = Nothing
  }
```

The `ihaskell install` command asks the GHC-API for the `libdir`, which only gives back one address. Would you be willing to look into it, and see if there's a way to fetch all possible libdirs? @orome

**Comment by orome** [comment] 2015-10-04 14:15
@gibiansky — I don't think that's what's happening here.

I only use Cabal to install packages, as far as I know. I used Homebrew to install `cabal-install` and then `cabal install` to install any and all packages. All the packages in both directories are visible to Cabal, and are updated correctly (each going to the appropriate directory). As far as I know that's a pretty standard configuration: iisn't the presence of a user and a global package database pretty standard (Cabal seems to thing so).

I've only use Stack to run `stack init` in a project directory, which, as you say, should have no effect on the rest of my installation.

**Comment by orome** [comment] 2015-10-04 14:17
@sumitsahrawat — So I'm not imagining things: `ihaskell install` is failing to use all the package directories?

**Comment by sumitsahrawat** [comment] 2015-10-04 16:27
> isn't the presence of a user and a global package database pretty standard

Yes. The global one is used when installing packages with `cabal install --global`, and the local one is used otherwise.

> So I'm not imagining things: ihaskell install is failing to use all the package directories?

Yup, exactly.

---

I couldn't recreate this, so this might be an issue with your configuration. I'll try and see if I can find something that may be causing the issue.

**Comment by sumitsahrawat** [comment] 2015-10-04 16:33
@orome Try this:

```bash
mv /Users/Rax/.ghc /Users/Rax/.ghc-backup
mv /Users/Rax/.cabal /Users/Rax/.cabal-backup
```

And then try to reinstall IHaskell.

**Comment by orome** [comment] 2015-10-04 16:52
What will that do to my Haskell installation? It looks like that will affect more than just IHaskell.

**Comment by sumitsahrawat** [comment] 2015-10-04 17:28
That will move aside all the packages installed locally to backup directories. It's harmless as you can revert it if IHaskell still doesn't work. If it does work, than this means that there is an issue with those directories, and you should just remove them.

**Comment by orome** [comment] 2015-10-04 18:08
But `ihaskell` is *in* one of those directories. (And nothing else Haskell-related has issues with them.)

**Comment by sumitsahrawat** [comment] 2015-10-04 18:30
You can try installing IHaskell in a sandbox, and then move aside the two directories. This is a last resort, and I'm as clueless as you are.

I thought it might be a bug in IHaskell, but I couldn't find anything. The `runGhc` function accepts a `Maybe FilePath`, which is where the libdir is used inside IHaskell, so there should not be any issue there.

The GHC-API documentation says that the output of `ghc --print-libdir` should be used there, which seems to be correctly stored in the kernelspec.

**Comment by gibiansky** [comment] 2015-10-04 18:52
@orome Do you have `stack` installed? (If you run the command `stack`, what does it tell you?)

**Comment by gibiansky** [comment] 2015-10-04 18:53
To clarify: IHaskell makes special accomodations for `stack`, and perhaps those are messing stuff up with your system.

**Comment by orome** [comment] 2015-10-04 19:32
@sumitsahrawat — I `mv`d and reinstalled everything (all my other packages too, of course) and now it seems to work.

@gibiansky — I reinstalled everything including `stack` (this time I installed it with `brew haskell-stack`). Running it just lists help.

**Comment by sumitsahrawat** [comment] 2015-10-04 22:36
Great :+1:. Closing as it seems to be fixed.

**Comment by orome** [comment] 2015-10-05 11:54
@sumitsahrawat — So for the record, what happened here? I had moved (after upgrading to OS X 10.11) from Haskell Platform to Homebrew Haskell, and reinstalled IHaskell and its dependencies. Everything *except* IHaskell worked. Was IHaskell holding on to something from the earlier Haskell setup?

**Comment by sumitsahrawat** [comment] 2015-10-05 12:50
When I change my `ghc` versions (on ArchLinux), it shows me a warning that I would have to replace some of my packages. The ones which I have to replace can be found out by `ghc-pkg list`.

It's possible that when shifting from Haskell Platform to Homebrew, you upgraded your GHC from some older version to 7.10.2. It still can't explain how `ghci` was able to function with them, though.

**Comment by orome** [comment] 2015-10-05 12:56
@sumitsahrawat — The GHC version was unchanged.

**Comment by orome** [comment] 2015-10-06 17:02
@gibiansky, @sumitsahrawat — This issue is back, exactly as before. I'm unable to import any packages from my user database in my (completely rebuilt and reinstalled) Haskell/Cabal/GHC installation.

I've done *nothing* since it did work except basic maintenance: `cabal update`, `cabal list`.

**Comment by gibiansky** [comment] 2015-10-06 17:19
My hypothesis is that this has to do with the entirely undocumented attempts at supporting `stack` in IHaskell. 

Specifically, IHaskell's behaviour now depends on the directory. If there's a `stack.yaml` file in the directory, it uses whatever snapshot it specifies, which may thus hide global things. Otherwise, it uses the global `stack` snapshot.

This worked for what I was doing at the time, but I can easily imagine now how different uses of stack, especially ones mixed with `cabal`, may yield incredibly confusing behaviour as a result of this.

I've pushed a commit to `master` that hides this behind a `--stack` flag. Try the latest `master`, and install with just `ihaskell install`, and see if that fixes things.

**Comment by orome** [comment] 2015-10-07 19:42
@gibiansky — Yes, that (using 3ebf5b074f) does the trick.

@sumitsahrawat — So just to put my mind at ease (I'm afraid to use Stack and Cabal now): there was nothing wrong with my configuration, right?

**Comment by sumitsahrawat** [comment] 2015-10-07 20:08
Most probably :smile:. I don't have much knowledge of the IHaskell internals, but going by what @gibiansky said, I don't think there was any issue with your config.

**Comment by gibiansky** [comment] 2015-10-09 06:15
@orome No, there probably was not.

**Closed by gibiansky** 2015-10-09 06:15 UTC

**Comment by orome** [comment] 2015-10-09 19:07
Does the latest Hackage release have this fixed yet?

**Comment by jluttine** [comment] 2016-10-02 15:02
Hi! I'm still experiencing similar issue that packages are not found in IHaskell.

Here are steps to reproduce from scratch (moved my current `~/.stack` elsewhere) and outside any project directories:

Set up:

```
stack setup --resolver=lts-6.15
```

Change resolver to lts-6.15:

```
vim ~/.stack/global-project/stack.yaml
```

Install IHaskell (make sure `~/.local/bin` is in `PATH`):

```
stack install ihaskell
stack exec ihaskell -- install --stack
```

Install some other package:

```
stack install hmatrix
```

Start Jupyter console:

```
stack exec jupyter -- console --kernel haskell
```

Try to import hmatrix:

```
In [1]: import Numeric.LinearAlgebra
      :     
Failed to load interface for ‘Numeric.LinearAlgebra’
Use -v to see a list of the files searched for.
```

Try GHCi for comparison:

```
stack exec ghci
```

Importing hmatrix works:

```
Prelude> import Numeric.LinearAlgebra
Prelude Numeric.LinearAlgebra> 
```

Any ideas what I'm missing?
