### ISSUE TITLE
macOS install script no longer works

### ISSUE THREAD

**Issue by defjaf** [gibiansky/IHaskell#711] opened 2017-03-08 10:02 UTC
I think largely because the default homebrew GHC installation is now 8.x, the macOS installation script now fails. (There are minor issues such as no longer being able to separately install `brew-cask` but those are relatively easy to patch by hand.) Is there still a straightforward non-docker way to install (since it looks like the GHC8 upgrade isn't happening soon...)?

This is related to (but because of the GHC8 issue) not the same as issue [704](https://github.com/gibiansky/IHaskell/issues/704).

**Comment by defjaf** [comment] 2017-03-08 10:05
Related to [704](https://github.com/gibiansky/IHaskell/issues/704).

**Comment by vaibhavsagar** [comment] 2017-03-15 10:52
I'm currently running this fork which seems to work well: https://github.com/abarbu/IHaskell

**Comment by abarbu** [comment] 2017-03-15 23:59
If you're willing to run a few tests on macOS we can easily get those instructions working if they aren't now. I just don't have a machine to test on.

**Comment by defjaf** [comment] 2017-03-16 09:53
I am happy to help, although my bandwidth for it is low at the moment. 

Is this a competing project, or is there a plan to reconcile the two?

**Comment by abarbu** [comment] 2017-03-16 10:16
It's neither a competing project nor do I have plans to submit a PR.

I just need a version for myself that always works in the latest Haskell ecosystem and I'm ok with maintaining one indefinitely. This is far easier given that I don't care about supporting old ghc/jupyter/stack versions or supporting running without stack (both of which burden this project) so I don't foresee my patches being useful or being pulled.

**Comment by alf239** [comment] 2017-04-16 19:44
@abarbu as far as I can tell, you can reach your goals using the following:

Edit the `macos-install.sh`, changing the lines 71-77 to:

```bash
# XQuartz is required: http://xquartz.macosforge.org/landing/
# The easiest way is through Homebrew.
brew tap Caskroom/cask
#brew      ls --versions brew-cask  | grep -q . || brew install brew-cask
brew cask ls --versions xquartz    | grep -q . || brew install Caskroom/cask/xquartz
brew      ls --versions cairo      | grep -q . || brew install cairo
brew      ls --versions pango      | grep -q . || brew install pango
```

That's based on [this StackOverflow question](http://stackoverflow.com/questions/23796448/homebrew-error-occurred-when-i-command-brew-cask-install-virtualbox-or-brew-c) basically stating that `brew install brew-cask` is now deprecated.

**Comment by alf239** [comment] 2017-04-16 19:46
A proper fix would require a decision based on the homebrew version (or a longer fallback chain), and testing it is going to be a bit of a pain. I'll try to read around and see what I can do, but for now just see the above.

**Comment by alf239** [comment] 2017-04-16 20:28
@abarbu apologies, noticed that you're not the one who raised the issue.

**Comment by alf239** [comment] 2017-04-17 16:56
@abarbu your version fails on Sierra, too, though:

```
--  While building package cairo-0.13.3.1 using:
      /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/cairo-0.13.3.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 configure --with-ghc=/Users/alf/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --with-ghc-pkg=/Users/alf/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/pkgdb --libdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/lib --bindir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/bin --datadir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/share --libexecdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/libexec --sysconfdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/etc --docdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/doc/cairo-0.13.3.1 --htmldir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/doc/cairo-0.13.3.1 --haddockdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/doc/cairo-0.13.3.1 --dependency=Cabal=Cabal-1.24.2.0 --dependency=array=array-0.5.1.1 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=gtk2hs-buildtools=gtk2hs-buildtools-0.13.2.2-DDnzCHJnxmeE0mZhuoMkdo --dependency=mtl=mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6 --dependency=text=text-1.2.2.1-Ji7hMs2U4BkBwavd4taEVR --dependency=utf8-string=utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/alf/Work/IHaskell/.stack-work/logs/cairo-0.13.3.1.log

    [1 of 2] Compiling Main             ( /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/cairo-0.13.3.1/Setup.hs, /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/cairo-0.13.3.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /Users/alf/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/cairo-0.13.3.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/cairo-0.13.3.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup ...
    Configuring cairo-0.13.3.1...
    setup: The pkg-config package 'cairo' version >=1.2.0 is required but it could
    not be found.


--  While building package glib-0.13.4.1 using:
      /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/glib-0.13.4.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 configure --with-ghc=/Users/alf/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --with-ghc-pkg=/Users/alf/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/pkgdb --libdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/lib --bindir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/bin --datadir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/share --libexecdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/libexec --sysconfdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/etc --docdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/doc/glib-0.13.4.1 --htmldir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/doc/glib-0.13.4.1 --haddockdir=/Users/alf/.stack/snapshots/x86_64-osx/lts-8.8/8.0.2/doc/glib-0.13.4.1 --dependency=Cabal=Cabal-1.24.2.0 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=containers=containers-0.5.7.1 --dependency=gtk2hs-buildtools=gtk2hs-buildtools-0.13.2.2-DDnzCHJnxmeE0mZhuoMkdo --dependency=text=text-1.2.2.1-Ji7hMs2U4BkBwavd4taEVR --dependency=utf8-string=utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/alf/Work/IHaskell/.stack-work/logs/glib-0.13.4.1.log

    [1 of 2] Compiling Main             ( /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/glib-0.13.4.1/Setup.hs, /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/glib-0.13.4.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /Users/alf/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/glib-0.13.4.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /private/var/folders/1x/lr4w9gn14qq5lgdy0lb00_bc0000gp/T/stack93235/glib-0.13.4.1/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup ...
    Configuring glib-0.13.4.1...
    setup: The pkg-config package 'glib-2.0' is required but it could not be
    found.
```

**Comment by abarbu** [comment] 2017-04-20 01:02
@alf239 I'm not surprised! I don't have a mac to test on. If you want to run some experiments we can figure out what's up and get it working.

**Comment by vaibhavsagar** [comment] 2017-06-27 16:42
@defjaf @alf239 is this still broken?

**Comment by alf239** [comment] 2017-06-27 20:51
@vaibhavsagar, I would suppose so, in the same way as mentioned above: `brew install brew-cask` is deprecated. As for `glib` and `cairo`, I was able to work around that by removing Anaconda and installing cairo manually.

**Comment by vaibhavsagar** [comment] 2017-06-27 23:58
Would you be willing to update the macOS install script with working instructions?

**Comment by alf239** [comment] 2017-06-28 06:12
@vaibhavsagar not in the next few weeks, I'm afraid — it's a task for a few hours (to get a clean slate Mac, try to reproduce the problem, isolate, check the solution, check the same against varying versions of Homebrew and whatnot, and write a reasonable explanatory text), and I'm not going to have that much spare time in the next two weeks. If you have a specific question, I'm happy to answer if I remember; a proper writeup/fix is not something I'm capable of at this point.

As far as I can see, the hints above are sufficient to get through most of the riddles _I_ encountered; there's nothing particularly tricky here. For me, the most painful part was to marry Homebrew with XCode without installing full XCode, and the solution for that was to give up.

**Comment by vaibhavsagar** [comment] 2017-06-28 06:46
I understand. I'd like to close this issue and the macOS instructions have been updated significantly since this issue was opened so I was hoping you would be able to have a quick look and confirm that the new instructions work better. A comprehensive writeup would be welcome but is certainly not expected.

**Closed** 2017-07-27 11:16 UTC
