### ISSUE TITLE
:doc and :hoogle on nixos

### ISSUE THREAD

**Issue by meditans** [gibiansky/IHaskell#340] opened 2015-01-22 16:16 UTC
Hi, I have some issues with the :doc and :hoogle commands (the rest works) on nixOS:
 
`:doc map` 
`No result: no matching identifiers found.`
`:hoogle map`
`No result: Failed reading: satisfy`

Do this commands use a local hoogle executables, or do they connect to a hoogle server to get the informations I'm missing?

Thanks
Carlo

**Comment by gibiansky** [comment] 2015-01-22 17:21
These commands use `hoogle`'s json output. Sounds like this is a json decoding issue.  Is there any reason why IHaskell would not be able to query something like this?
```
https://www.haskell.org/hoogle/?hoogle=test&mode=json
```

**Comment by meditans** [comment] 2015-01-22 17:55
No, if you do that with a web link, I can't think of a reason. I'm using ihaskell-4.2.36 on nixos-unstable. Pinging @edwtjo, however, he probably knows more.

**Comment by edwtjo** [comment] 2015-01-23 10:49
Confirmed, this is probably nix-related and I'll look into it.

**Comment by gitfoxi** [comment] 2015-01-27 19:05
I installed using Docker yesterday and have the same problem.

**Comment by edwtjo** [comment] 2015-01-31 09:16
@gitfoxi IHaskell doesn't use a local hoogle process. It uses http-client to send it's requests to an external instance at haskell.org, as specified by @gibiansky. What you're seeing are exceptions tossed back from an exception in http-client. 

*I hypothesize this is caused by GHC's compile time [non-determinism](https://ghc.haskell.org/trac/ghc/ticket/4012) which breaks the ABI between local and remotely compiled libraries, like what you commonly get with hydra. So when we enter that loadpath the runtime system can't find a compatible dynlib and shits itself.*

I have yet to confirm this though but, either way, I really don't like the idea of a static IHaskell build for nixpkgs.

**Comment by gibiansky** [comment] 2015-02-12 06:49
I am closing this as a nix-related issue. If there's anything I can do to fix this (or any way to reproduce this on Linux or preferably Mac) I am happy to assist somewhat, in which case, please reopen the bug!

**Closed by gibiansky** 2015-02-12 06:49 UTC
