### ISSUE TITLE
ihaskell: Error casting types in Evaluate.hs

### ISSUE THREAD

**Issue by vaibhavsagar** [gibiansky/IHaskell#659] opened 2016-04-27 13:41 UTC
Steps to reproduce:

1. `pipsi install jupyter-core` (and install other packages so that Jupyter works)
2. `git clone git@github.com:gibiansky/IHaskell.git; cd IHaskell; stack install`
3. `source ~/.local/venvs/jupyter-core/bin/activate`
4. `ihaskell install`
5. `stack exec jupyter -- notebook` or `stack exec jupyter -- console --kernel haskell`
6. Try using a notebook or the REPL.

This only started happening on Ubuntu 16.04. Could this be the issue?

**Comment by bzdzb** [comment] 2016-05-06 13:34
YMMV, but I was able to get IHaskell installed on Ubuntu 16.04 by doing:

1. `pipsi install jupyter-core` (and install other packages so that Jupyter works)
2. `apt-get install -y libmagic-dev libncurses5-dev pkg-config libcairo2-dev liblapack-dev libblas-dev libpangocairo-1.0 libpango1.0-dev libzmq5-dev libzmq5`
3. `git clone git@github.com:gibiansky/IHaskell.git && cd IHaskell`
4. `source ~/.local/venvs/jupyter-core/bin/activate`
5. `stack setup && stack build && stack install`
6. `pip install jupyter` (after jupyter-core venv is activated)
7. `ihaskell install`
8. `stack exec jupyter -- notebook` || `stack exec jupyter -- console --kernel haskell`

Just a guess, but I suspect the problem you're seeing may be related to a ghc version incompatibility with one of the dependency versions.

**Comment by vaibhavsagar** [comment] 2016-05-06 13:48
Thanks for the update! I followed your instructions and this time I'm getting #636 but with `cryptonite-0.15`. This is a step in the right direction :smile:

**Comment by thomasjm** [comment] 2016-06-09 04:40
I'm getting this same problem, and confused why @bzdzb's instructions helped (what does having Jupyter in a virtualenv have to do with IHaskell building properly?)

I'm building the HEAD version of IHaskell using the current resolver `nightly-2016-03-25` and having no luck. I put some print statements in the function in question:

```haskell
-- | Compile a string and extract a value from it. Effectively extract the result of an expression
-- from inside the notebook environment.
extractValue :: Typeable a => String -> Interpreter a
extractValue expr = do
  print "The expr:"
  print expr
  compiled <- dynCompileExpr expr
  print "The compiled thing: "
  print compiled
  case fromDynamic compiled of
    Nothing     -> error "Error casting types in Evaluate.hs"
    Just result -> return result
```

which gives me the result

```
> jupyter console --kernel haskell
Run from outside a project, using implicit global project config
Jupyter Console 4.0.3

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic

In [1]: print 42
"The expr:"
"IHaskell.Display.displayFromChan"
"The compiled thing: "
<<IO (Maybe Display)>>
ihaskell: Error casting types in Evaluate.hs
kernel died, restart ([y]/n)? n
```

It seems that `dynCompileExpr` is a basic function from the GHC API, so something very basic seems to be going wrong...any chance you know what's going on @gibiansky ? My only thought is that my `ghclib` is wrong somehow, but it's just the one created by stack at `~/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3`

**Comment by gibiansky** [comment] 2016-06-09 06:36
I've been debugging this very recently actually.

This happens when there are *two* versions of IHaskell installed, and the version of the IHaskell library being loaded into IHaskell differs from the version it was compiled with. 

If you execute something like, `find .stack-work/dist -name 'libHSihaskell*.dylib'`, do you see multiple results? (Different hash strings in the `0.8.4.0-HASH-ghc7.10.3.dylib` part?)

**Comment by gibiansky** [comment] 2016-06-09 06:38
If you are getting this when running `stack test` (that is where I have been encountering this most) the problem seems to be fixed up upgrading to the latest stack with `stack upgrade --git`. (Make sure to `rm -rf .stack-work` and `stack clean` in this case.)

**Comment by thomasjm** [comment] 2016-06-09 07:42
Yes, I see a bunch of `libHSihaskell` files in my IHaskell/.stack-work folder actually:

```
.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/libHSihaskell-0.8.3.0-1bhTkkRBeEPLAA5brKGblL.a
.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/libHSihaskell-0.8.3.0-1bhTkkRBeEPLAA5brKGblL-ghc7.10.2.so
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/libHSihaskell-0.8.4.0-2RylCIRlEOM2to8yn1N7ME.a
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/libHSihaskell-0.8.4.0-2iza7YrPXR2J9b4Q4i0o2A.a
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/libHSihaskell-0.8.4.0-DJhm1iydlaT3a9fQPEhe13.a
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/libHSihaskell-0.8.4.0-2iza7YrPXR2J9b4Q4i0o2A-ghc7.10.3.so
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/libHSihaskell-0.8.4.0-2RylCIRlEOM2to8yn1N7ME-ghc7.10.3.so
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/libHSihaskell-0.8.4.0-DJhm1iydlaT3a9fQPEhe13-ghc7.10.3.so
```

It's not during `stack test`, but I'll try upgrading stack and see if anything good happens...

**Comment by gibiansky** [comment] 2016-06-09 08:49
Yeah, that is definitely the root cause here. Any idea how that happens?

Basically the issue is that when IHaskell is compiled w/ different settings it creates different versions of its types. When IHaskell version 1 tries to load some data type that is created by a compiled version of IHaskell version 2, the Typeable fingerprints don't match, and so everything comes crashing down.

One *possibility* is to try and HIDE those packages from IHaskell so it doesn't load them... but I imagine that could cause _more_ confusion, as if you install, say, ihaskell display packages, and they SILENTLY don't work because they are for a different "version" of IHaskell. 

Another possibility is to add an up-front check that yells at the user if they have somehow gotten into this scenario.

I'd really like to know _why_ this happens, and if there's anything I can do to fix it or work around it.

**Comment by gibiansky** [comment] 2016-06-09 08:49
By the way, you _can_ just `rm -rf .stack-work` to remove all of them. That can sometimes help even on older version of Stack

**Comment by thomasjm** [comment] 2016-06-09 17:27
I completely removed ~/.stack and IHaskell/.stack-work and rebuilt and then `jupyter console --kernel haskell` worked, so that's good.

Then I made the problem come back by doing the following:

1) Build from scratch another project that has `ihaskell-diagrams` as a dependency (I added this in an attempt to get diagrams to work--I was getting the old "Failed to load interface IHaskell.Display")
2) Now, `jupyter console --kernell haskell` fails with `Error casting types in Evaluate.hs` both inside that project and also *outside*

Evidently just building another project that depends on IHaskell is enough to mess up the whole system. (I was even using the same resolver.) I'll keep experimenting with this...

**Comment by thomasjm** [comment] 2016-06-09 17:31
+1 for a solution that involves checking the version of the IHaskell display packages and complaining loudly when they mismatch--I've found the display stuff to be pretty fragile when building things different ways

**Comment by gibiansky** [comment] 2016-06-09 18:15
It seems that by adding `ihaskell-diagrams` as a dependency, you have installed a second version of `ihaskell` itself (in the same resolver), which is now causing problems...

Another possibility is to avoid having a dependency like this – never cast values that come from another IHaskell. Instead, serialize all values to ByteString or something like that, which is outside of IHaskell...

I'm going to try to reproduce this issue very concisely inside a Docker container – this is a real hassle and has been plaguing IHaskell for years at this point I think, so it's worth investing time into finding a real fix.

**Comment by gibiansky** [comment] 2016-06-09 18:45
I've managed to reproduce this as follows:

1. Build via `stack build`.
2. Build a profiling copy via `stack build --library-profiling`.
3. Rebuild via `stack build`.
4. Verify that it's now broken via something like `stack exec .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/hspec/hspec`. (For me `stack test` rebuilds `ihaskell` again and it works after that)

I'm going to try to patch this by making sure that all uses of `extractValue` do not transfer values that are part of `ihaskell`'s library by encoding them to bytestring first.

**Comment by thomasjm** [comment] 2016-06-09 20:20
That patch sounds great, hope it works! Thanks for the quick response

**Comment by gibiansky** [comment] 2016-06-10 16:57
For posterity, simpler method of reproducing this: `stack clean; stack test; timeout 1s stack build --library-profiling; stack build; stack exec .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/hspec/hspec`

**Comment by gibiansky** [comment] 2016-06-10 18:10
This should be fixed on master. (Although issues with widgets can still arise, but a warning will be issued instead of crashing)

**Closed by gibiansky** 2016-06-10 18:10 UTC

**Comment by thomasjm** [comment] 2016-06-10 20:17
Awesome, thanks!!!
