### ISSUE TITLE
Flags cannot contain spaces

### ISSUE THREAD

**Issue by houshuang** [gibiansky/IHaskell#371] opened 2015-02-24 01:12 UTC
Flags cannot contain spaces and arguments, leading to something like

```haskell
:set -package ghc-paths
```

which works fine in GHCi, to fail.

**Comment by gibiansky** [comment] 2015-03-05 07:56
We currently use [`parseDynamicFlagsCmdline`](https://www.haskell.org/platform/doc/2013.2.0.0/ghc-api/src/DynFlags.html#parseDynamicFlagsCmdLine) for parsing flags in `Utils`, which should be fine. The issue is in `Evaluate.hs:469`, where we only pass the first flag to `Util.setFlags`.

This issue happens because we allow setting things that aren't GHC flags via `set`, such as `+t`. We should maintain this for compatibility with GHCi. Looks like we need a smarter parsing algorithm though -- perhaps just extract all the special non-GHC flags from the list of flags, then pass the rest to `setFlags`.

**Comment by gibiansky** [comment] 2015-03-16 09:27
Fixed in #431, though `package` flag not yet supported

**Closed by gibiansky** 2015-03-16 09:27 UTC
