### ISSUE TITLE
Current directory

### ISSUE THREAD

**Issue by FranklinChen** [gibiansky/IHaskell#425] opened 2015-03-09 17:21 UTC
I got confused when all notebooks that try to read a relative path (e.g. with `readFile`) failed because the path is no longer the expected path to an external resource, because IPython thinks the current directory (as reported in a notebook with `getCurrentDirectory`) is my original GitHub repo clone build directory.

I do see various calls to `setCurrentDirectory` in the source code but am not sure what behavior is intended and therefore what is a bug or not:

```console
$ ack setCurrentDirectory
Hspec.hs
60:  getTemporaryDirectory >>= setCurrentDirectory
153:      where cdEvent path = liftIO $ setCurrentDirectory path --Eval.evaluate defaultKernelState (":! cd " ++ path) noPublish

src/IHaskell/Display.hs
48:import System.Directory(getTemporaryDirectory, setCurrentDirectory)
161:      setCurrentDirectory

src/IHaskell/Eval/Evaluate.hs
575:        liftIO $ setCurrentDirectory directory
578:        let cmd = printf "IHaskellDirectory.setCurrentDirectory \"%s\"" $

src/Main.hs
139:  setCurrentDirectory $ initDir initInfo
```

**Comment by gibiansky** [comment] 2015-03-09 19:49
I'm not sure what the intended behaviour was either, actually, now that I think about it. I remember having a discussion about this earlier and fixing some issues, but it was a while ago.

I also think that the desired behaviour is going to change to be a better behaved Jupyter kernel. Specifically, I'd like to get rid of `ihaskell console`, `ihaskell notebook`, and `ihaskell view`, and make it so that with respect to the directory it behaves the same as the IPython kernel.

**Comment by gibiansky** [comment] 2015-03-11 05:19
I think this should be fixed as of https://github.com/gibiansky/IHaskell/pull/428 being merged. It should now work identically to `ipython`.

**Closed by gibiansky** 2015-03-11 05:19 UTC

**Comment by FranklinChen** [comment] 2015-03-11 14:54
Yes, this is fixed now, thanks! Various existing IHaskell notebooks hadn't been working.
