### ISSUE TITLE
fmap causing kernel to hang.

### ISSUE THREAD

**Issue by capn-freako** [gibiansky/IHaskell#622] opened 2015-12-25 15:45 UTC
The following code seems to cause the kernel (7.10.3) to hang, in a notebook, while running fine in ghci:

```
x = Just 1
:t x
x
y = id <$> x
:t y
y
```

(Of course, in ghci, there are "let"s in front of "x = ..." and "y = ...".)

Changing "id" to "(+ 1)" produces the expected result:

```
x :: forall a. Num a => Maybe a
Just 1
y :: forall b. Num b => Maybe b
Just 2
```

**Comment by gibiansky** [comment] 2015-12-25 18:08
Is there any error output from the console? This seems very strange.

**Comment by capn-freako** [comment] 2015-12-29 00:09
Sorry, I don't seem to be able to launch the console:

Davids-MacBook-Air-2:fft-ccc dbanas$ ipython console --kernel haskell
Traceback (most recent call last):
  File "/Users/dbanas/anaconda/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/dbanas/anaconda/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named jupyter_console.app

**Comment by capn-freako** [comment] 2015-12-29 01:25
I'm not sure whether this is helpful, but this:

    Just id <*> Nothing

works, while this:

    (Just id <*> Nothing) == Nothing

causes the kernel to hang.

**Comment by capn-freako** [comment] 2015-12-29 15:47
This simpler test also causes the kernel to hang:

    Nothing == Nothing

**Comment by gibiansky** [comment] 2015-12-29 18:48
@capn-freako Thanks for the report. Just managed to reproduce this.

Very strange behaviour. I'll try to figure out what's going on soon. Whatever it is, it's very strange:
```haskell
-- works
x = Just id <*> Nothing

-- doesn't work
x = (Just id <*> Nothing)
```

I have _no clue_ what could cause something like this or how it is just being reported now.

**Comment by franklx** [comment] 2016-01-20 12:07
I tried 7.10.2 and 7.10.3 on archlinux x86_64: same problem.
Apparently this is caused by a deadlock in `runStmt` at: 
```haskell
goStmt :: String -> Ghc RunResult
goStmt s = runStmt s RunToCompletion
```
but I don't know how to debug it.

**Comment by franklx** [comment] 2016-01-20 22:46
Kernel doesn't hang but "teminates the zmq context":
```
ihaskell: ZMQError { errno = 156384765, source = "getIntOpt", message = "Context was terminated" }
ihaskell: ZMQError { errno = 156384765, source = "getIntOpt", message = "Context was terminated" }
ihaskell: ZMQError { errno = 156384765, source = "send", message = "Context was terminated" }
ihaskell: printf: formatting string ended prematurely
```

**Comment by franklx** [comment] 2016-01-21 13:30
Finally i figured out what's happening.
Code snippets that cause crash doesn't seem to have nothing in common - but they have it instead!
Running "Nothing == Nothing" gives an unexpected result _before_ evaluation:
```
Line 1: Use isNothing
Found:
Nothing == Nothing
Why not:
isNothing NothingLine 1: Use isNothing
Found:
Nothing == Nothing
Why not:
isNothing Nothing
```
The reply is unexpected and makes the zeromq communication stop - the ihaskell kernel continues to run!
Being an haskell beginner I don't know how to disable this message (it appears to be an interactive GHC hint).
BTW disabling these "hints" is just a workaround so it could be a good idea showing this messages in Jupyter pager pane.

**Comment by franklx** [comment] 2016-01-21 13:42
It's the ihaskell lint causing the problem.
Disabling it with:
```
:opt no-lint
```
solves the problem (e.g. kernel doesn't hang anymore).
As I told before it's just a workaround.

**Comment by franklx** [comment] 2016-01-21 13:59
It's a _small_slip_ in the Lint code:
```diff
--- a/src/IHaskell/Eval/Lint.hs
+++ b/src/IHaskell/Eval/Lint.hs
@@ -187,7 +187,7 @@ htmlSuggestions = concatMap toHtml
             _ -> "warning"

     style :: String -> String -> String
-    style =  printf "<div class=\"suggestion-${cls}\">%s</div>"
+    style =  printf "<div class=\"suggestion-%s\">%s</div>"

     named :: String -> String
     named = printf "<div class=\"suggestion-name\" style=\"clear:both;\">%s</div>"
```
Do you need a pull request?

**Comment by sumitsahrawat** [comment] 2016-01-21 14:45
Thanks for finding the fix!! You can send a PR if you want, otherwise I'll be happy to apply the patch.

**Comment by gibiansky** [comment] 2016-01-26 07:49
Thanks @franklx for handling this one, closing

**Closed by gibiansky** 2016-01-26 07:49 UTC
