### ISSUE TITLE
kernel always restart, console display ihaskell: setEnv: invalid argument

### ISSUE THREAD

**Issue by ncaq** [gibiansky/IHaskell#823] opened 2018-02-13 06:57 UTC
error screenshot

![screenshot-2018-02-13-15-54-32](https://user-images.githubusercontent.com/2913112/36136960-3f1b9936-10d6-11e8-992e-499c8b72b264.png)

error log

~~~
2018-02-13T15:46:05 ncaq@strawberry/pts/3(0) ~
% stack exec jupyter -- notebook
[I 15:46:07.420 NotebookApp] Serving notebooks from local directory: /home/ncaq
[I 15:46:07.421 NotebookApp] 0 active kernels 
[I 15:46:07.421 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=95808454c58b22e92c7a11ad7905c92d155913272abcae2f
[I 15:46:07.421 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:46:07.421 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=95808454c58b22e92c7a11ad7905c92d155913272abcae2f
[I 15:46:07.666 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 15:46:08.601 NotebookApp] /home/ncaq/.steampath doesn't exist
[I 15:46:13.343 NotebookApp] 302 GET /?token=95808454c58b22e92c7a11ad7905c92d155913272abcae2f (::1) 0.64ms
[W 15:46:13.421 NotebookApp] 404 GET /robots.txt (::1) 10.81ms referer=None
[W 15:46:14.189 NotebookApp] /home/ncaq/.steampath doesn't exist
[I 15:46:25.374 NotebookApp] Creating new notebook in 
[I 15:46:26.616 NotebookApp] Kernel started: 61a0c7b6-02cf-4d28-93bb-bfd0b42e5d86
[W 15:46:26.710 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180213154607 (::1) 2.20ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
ihaskell: setEnv: invalid argument
[W 15:46:27.059 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20180213154607 (::1) 1.48ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
[I 15:46:29.617 NotebookApp] KernelRestarter: restarting kernel (1/5)
ihaskell: setEnv: invalid argument
[I 15:46:32.624 NotebookApp] KernelRestarter: restarting kernel (2/5)
ihaskell: setEnv: invalid argument
[I 15:46:35.630 NotebookApp] KernelRestarter: restarting kernel (3/5)
ihaskell: setEnv: invalid argument
[W 15:46:36.747 NotebookApp] Timeout waiting for kernel_info reply from 61a0c7b6-02cf-4d28-93bb-bfd0b42e5d86
[I 15:46:38.636 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 61a0c7b6-02cf-4d28-93bb-bfd0b42e5d86 restarted
ihaskell: setEnv: invalid argument
[W 15:46:41.643 NotebookApp] KernelRestarter: restart failed
[W 15:46:41.644 NotebookApp] Kernel 61a0c7b6-02cf-4d28-93bb-bfd0b42e5d86 died, removing from map.
ERROR:root:kernel 61a0c7b6-02cf-4d28-93bb-bfd0b42e5d86 restarted failed!
[W 15:46:41.678 NotebookApp] Kernel deleted before session
[W 15:46:41.679 NotebookApp] 410 DELETE /api/sessions/a52f9770-76bb-4237-bfbd-8fe09c5364ca (::1) 1.85ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
[W 15:46:42.840 NotebookApp] Session not found: session_id='a52f9770-76bb-4237-bfbd-8fe09c5364ca'
[W 15:46:42.840 NotebookApp] 404 DELETE /api/sessions/a52f9770-76bb-4237-bfbd-8fe09c5364ca (::1) 1.37ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
[I 15:46:42.880 NotebookApp] Kernel started: 160dbb17-3c95-4e2c-a340-0f713a697591
ihaskell: setEnv: invalid argument
[W 15:46:44.405 NotebookApp] /home/ncaq/.steampath doesn't exist
[I 15:46:45.881 NotebookApp] KernelRestarter: restarting kernel (1/5)
ihaskell: setEnv: invalid argument
[I 15:46:48.888 NotebookApp] KernelRestarter: restarting kernel (2/5)
ihaskell: setEnv: invalid argument
[I 15:46:51.895 NotebookApp] KernelRestarter: restarting kernel (3/5)
ihaskell: setEnv: invalid argument
[W 15:46:52.916 NotebookApp] Timeout waiting for kernel_info reply from 160dbb17-3c95-4e2c-a340-0f713a697591
[I 15:46:54.901 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 160dbb17-3c95-4e2c-a340-0f713a697591 restarted
ihaskell: setEnv: invalid argument
[W 15:46:57.909 NotebookApp] KernelRestarter: restart failed
[W 15:46:57.910 NotebookApp] Kernel 160dbb17-3c95-4e2c-a340-0f713a697591 died, removing from map.
ERROR:root:kernel 160dbb17-3c95-4e2c-a340-0f713a697591 restarted failed!
[W 15:46:57.965 NotebookApp] Kernel deleted before session
[W 15:46:57.965 NotebookApp] 410 DELETE /api/sessions/cd3ecbd8-e8a9-4884-9b48-ac94c99e36ee (::1) 1.76ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
[I 15:48:26.574 NotebookApp] Saving file at /Untitled.ipynb
[W 15:49:00.472 NotebookApp] /home/ncaq/.steampath doesn't exist
[W 15:51:09.284 NotebookApp] /home/ncaq/.steampath doesn't exist
~~~

system infomation

~~~
2018-02-13T15:53:21 ncaq@strawberry/pts/0(1) ~
% stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
2018-02-13T15:53:22 ncaq@strawberry/pts/0(0) ~
% cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
2018-02-13T15:54:17 ncaq@strawberry/pts/0(0) ~
% python --version
Python 3.5.4
~~~

~/.stack/global-project/stack.yaml

~~~yaml
# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/ncaq/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-10.4
# flags:
#   xmobar:
#     with_threaded: true
#     with_utf8: true
#     with_xft: true
~~~

**Comment by ncaq** [comment] 2018-02-15 06:44
> Can you try this from the directory you cloned IHaskell to?

I will try it when I go home.

> Do you have any idea why you're getting /home/ncaq/.steampath doesn't exist because I haven't seen that before.

This probably does not matter, but I just submitted that it is mixed in the error message.

**Comment by ncaq** [comment] 2018-02-16 09:25
I tried running stack exec jupyter -- notebook in the cloned directory and it worked fine.
In my case ~/Downloads/IHaskell.
It seems that it is not written in the document that it does not work outside of the cloned directory, is it a specification?
I have performed stack install and ihaskell install --stack as documented.

**Comment by vaibhavsagar** [comment] 2018-02-16 11:18
It does work outside the cloned directory, but I suspect something else might be going on with your setup. Installing with `--stack` means that IHaskell will work best when invoked from within a Stack project directory though. What is the output of `stack exec -- which ihaskell` when run from your home directory?

**Comment by vaibhavsagar** [comment] 2018-02-16 18:32
Also, what happens if you start IHaskell from within a fresh Stack project? I would expect this to work:

```bash
$ stack new ihaskell-test
$ cd ihaskell-test
$ stack exec -- jupyter notebook
```

**Comment by ncaq** [comment] 2018-02-25 06:42
> you start IHaskell from within a fresh Stack project?

I tried to go but it did not work.

~~~
2018-02-25T15:37:23 ncaq@strawberry/pts/1(0) ~/Downloads/ihaskell-test
% stack exec -- jupyter notebook
[I 15:37:29.471 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 15:37:29.666 NotebookApp] Serving notebooks from local directory: /home/ncaq/Downloads/ihaskell-test
[I 15:37:29.666 NotebookApp] 0 active kernels 
[I 15:37:29.666 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=e8d308d63349384bbd89ffa8238b1ec512de25ad87ae0b2c
[I 15:37:29.666 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:37:29.667 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=e8d308d63349384bbd89ffa8238b1ec512de25ad87ae0b2c
[I 15:37:29.917 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 15:37:29.966 NotebookApp] 404 GET /robots.txt (::1) 6.75ms referer=None
[I 15:37:37.694 NotebookApp] Creating new notebook in 
[I 15:37:38.840 NotebookApp] Kernel started: ec813ef2-aa40-42c4-8ac8-90e1fcc3eccf
[W 15:37:38.890 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180225153729 (::1) 1.75ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
ihaskell: setEnv: invalid argument
[W 15:37:39.150 NotebookApp] 404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20180225153729 (::1) 2.34ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
[I 15:37:41.841 NotebookApp] KernelRestarter: restarting kernel (1/5)
ihaskell: setEnv: invalid argument
[I 15:37:44.848 NotebookApp] KernelRestarter: restarting kernel (2/5)
ihaskell: setEnv: invalid argument
[I 15:37:47.855 NotebookApp] KernelRestarter: restarting kernel (3/5)
ihaskell: setEnv: invalid argument
[W 15:37:48.938 NotebookApp] Timeout waiting for kernel_info reply from ec813ef2-aa40-42c4-8ac8-90e1fcc3eccf
[I 15:37:50.861 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel ec813ef2-aa40-42c4-8ac8-90e1fcc3eccf restarted
ihaskell: setEnv: invalid argument
[W 15:37:53.868 NotebookApp] KernelRestarter: restart failed
[W 15:37:53.868 NotebookApp] Kernel ec813ef2-aa40-42c4-8ac8-90e1fcc3eccf died, removing from map.
ERROR:root:kernel ec813ef2-aa40-42c4-8ac8-90e1fcc3eccf restarted failed!
[W 15:37:53.902 NotebookApp] Kernel deleted before session
[W 15:37:53.903 NotebookApp] 410 DELETE /api/sessions/3de0b203-6592-47d3-a5b8-d10e753d1469 (::1) 2.08ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=haskell
^C[I 15:38:05.015 NotebookApp] interrupted
Serving notebooks from local directory: /home/ncaq/Downloads/ihaskell-test
0 active kernels 
The Jupyter Notebook is running at: http://localhost:8888/?token=e8d308d63349384bbd89ffa8238b1ec512de25ad87ae0b2c
Shutdown this notebook server (y/[n])? y
[C 15:38:05.695 NotebookApp] Shutdown confirmed
[I 15:38:05.696 NotebookApp] Shutting down kernels
^C
~~~

You may have understood the cause.
I am using xmonad as a window manager.
xmonad works with stack.
So stack will change PATH.

There are my PATH.

~~~
2018-02-25T15:38:20 ncaq@strawberry/pts/1(130) ~/Downloads/ihaskell-test
% echo $PATH
/home/ncaq/.stack/global-project/.stack-work/install/x86_64-linux-ncurses6-nopie/lts-10.4/8.2.2/bin:/home/ncaq/.stack/snapshots/x86_64-linux-ncurses6-nopie/lts-10.4/8.2.2/bin:/home/ncaq/.stack/compiler-tools/x86_64-linux-ncurses6-nopie/ghc-8.2.2/bin:/home/ncaq/.stack/programs/x86_64-linux/ghc-ncurses6-nopie-8.2.2/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin:/opt/cuda/bin:/home/ncaq/.local/bin:/home/ncaq/.config/yarn/global/node_modules/.bin/:/sbin:/usr/sbin:/usr/games/bin:/home/ncaq/.local/bin:/home/ncaq/.config/yarn/global/node_modules/.bin
~~~

If this is the cause, it means that xmonad users can not be supported.
I think that you should write that xmonad users can only use them directly under the directory.
Or rewrite the setEnv part so that the window manager user who uses stack like xmonad can also run it.
I am not quite familiar with IHaskell so I do not know how to fix it properly.

**Comment by vaibhavsagar** [comment] 2018-02-25 06:45
I don't understand what the problem is, but it sounds like you do. Can you also provide the output of `stack exec -- echo $PATH` for me to compare?

**Comment by ncaq** [comment] 2018-02-26 02:53
~~~
2018-02-26T11:52:29 ncaq@strawberry/pts/1(0) ~
% stack exec -- echo $PATH
/home/ncaq/.stack/global-project/.stack-work/install/x86_64-linux-ncurses6-nopie/lts-10.4/8.2.2/bin:/home/ncaq/.stack/snapshots/x86_64-linux-ncurses6-nopie/lts-10.4/8.2.2/bin:/home/ncaq/.stack/compiler-tools/x86_64-linux-ncurses6-nopie/ghc-8.2.2/bin:/home/ncaq/.stack/programs/x86_64-linux/ghc-ncurses6-nopie-8.2.2/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/5/bin:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin:/opt/cuda/bin:/home/ncaq/.local/bin:/home/ncaq/.config/yarn/global/node_modules/.bin/:/sbin:/usr/sbin:/usr/games/bin:/home/ncaq/.local/bin:/home/ncaq/.config/yarn/global/node_modules/.bin
~~~

**Comment by vaibhavsagar** [comment] 2018-11-14 19:20
Closing this, please reopen if necessary.

**Closed by vaibhavsagar** 2018-11-14 19:20 UTC
