### ISSUE TITLE
Recent Stack LTS versions don't seem to work

### ISSUE THREAD

**Issue by peddie** [gibiansky/IHaskell#636] opened 2016-02-09 13:24 UTC
I installed `ihaskell` completely from scratch using `stack` LTS 5.2 on two different machines running debian x86_64:

```
stack install --no-system-ghc ihaskell && stack exec --no-system-ghc ihaskell -- install --stack && stack exec --no-system-ghc jupyter -- notebook --debug --no-browser --ip=<IP address>
```

I encountered the same error in both cases:

```
ihaskell: /home/peddie/.stack/snapshots/x86_64-linux/lts-5.2/7.10.3/lib/x86_64-linux-ghc-7.10.3/cryptonite-0.10-9z0j8QI27Av2VIWw0mEkTO/libHScryptonite-0.10-9z0j8QI27Av2VIWw0mEkTO.a: unhandled ELF relocation(RelA) type 42

ihaskell: ihaskell: unable to load package `cryptonite-0.10'
[I 22:50:20.392 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

`stack exec --no-system-ghc ghc-pkg -- list` has no trouble locating `cryptonite`.  `stack exec --no-system-ghc ghci` has no trouble loading and running functions from `Crypto.Random.EntropyPool` (to choose a random example).

My `kernel.json` file:

```
peddie@endeavour:~$ cat /home/peddie/.local/share/jupyter/kernels/haskell/kernel.json
{"display_name":"Haskell","argv":["/home/peddie/.stack/snapshots/x86_64-linux/lts-5.2/7.10.3/bin/ihaskell","kernel","{connection_file}","--ghclib","/home/peddie/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/","--stack"],"language":"haskell"}
```

This file was created with `/opt/ghc/7.10.3/lib/ghc-7.10.3/` in the `--ghclib` field of `kernel.json`, but the error did not go away when I manually replaced it with the path to `stack`'s libs.

EDIT: I forgot a critical piece of information: this issue does not occur when building with stackage LTS 5.1, which also uses `cryptonite-0.10`.

**Comment by Jiehong** [comment] 2016-03-09 21:50
I hot the same issue before, but all seems well with stack lts-5.6 so far.

**Comment by peddie** [comment] 2016-03-14 04:20
I still experience the exact same issue with stack lts-5.6 or 5.5 on debian sid x86_64, on multiple machines.

**Comment by Hodapp87** [comment] 2016-04-12 21:33
I'm experiencing this issue as well on ArchLinux. I tried the command at the top of the first post as well.

**Comment by xavier83** [comment] 2016-05-06 07:38
same with lts-5.15 :disappointed:

**Comment by rpglover64** [comment] 2016-05-10 03:51
The following seemed to fix the issue for me:

1. add
    ```
    ghc-options:
      cryptonite: -opta-Wa,-mrelax-relocations=no
    ```

    to the `stack.yaml` file (that's what my PR does).
2. Run `stack exec -- ghc-pkg unregister cryptonite --force` (otherwise stack won't rebuild `cryptonite`, and the options won't have any effect.
3. Run `stack build` (I ran `stack build --force-dirty`, but I think it may not be necessary)

**Comment by vaibhavsagar** [comment] 2016-05-11 02:22
Hi @rpglover64, I tried this and I now have a working kernel again, although `stack exec -- ghc-pkg unregister cryptonite --force` didn't seem to have any effect. Instead I got this output:
```
unregistering would break the following packages: http-client-tls-0.2.2 connection-0.2.5 tls-1.3.4 x509-validation-1.6.3 x509-system-1.6.3 x509-store-1.6.1 x509-1.6.3 ihaskell-diagrams-0.3.1.0 ihaskell-widgets-0.2.3.1 ihaskell-rlangqq-0.3.0.0 ihaskell-static-canvas-0.1.0.0 ihaskell-plot-0.3.0.0 ihaskell-magic-0.3.0.0 ihaskell-aeson-0.3.0.0 ihaskell-charts-0.3.0.0 ihaskell-hatex-0.2.1.0 ihaskell-juicypixels-1.1.0.0 ihaskell-basic-0.3.0.0 ihaskell-gnuplot-0.1.0.0 ihaskell-blaze-0.3.0.0 ihaskell-0.8.4.0 (ignoring)
```

**Comment by rpglover64** [comment] 2016-05-11 14:38
@vaibhavsagar That's the expected message: the "(ignoring)" is `ghc-pkg` ignoring the fact that it would break things and unregistering anyway; without that line, `stack` won't (or at least didn't for me) recompile `cryptonite`.

You may run into the same issue in other packages as you use `IHaskell` (e.g. `glib` if you try to render `diagrams`), but the same process has worked for me so far.

**Comment by Shimuuar** [comment] 2016-05-23 14:46
One more observation about issue. I tried @rpglover64 's solution using lts-5.17 with stack-1.0.4.3 and 1.1.2. It works with 1.0.4.3 and fails with 1.1.2. Why? I have no idea

**Comment by gibiansky** [comment] 2016-06-09 08:46
LTS 6.2 should definitely work at the moment.

**Comment by xavier83** [comment] 2016-06-09 12:15
no luck for me even after updating to LTS 6.2, getting the following error message in the console

```
404 GET /static/components/codemirror/mode/ihaskell/ihaskell.js?v=20160609174125 (::1) 5.73ms referer=http://localhost:8888/notebooks/Demo.ipynb
ihaskell: /home/user/.stack/snapshots/x86_64-linux/lts-6.2/7.10.3/lib/x86_64-linux-ghc-7.10.3/cryptonite-0.15-F8W9M5THBW4FIZAr1UOHUh/libHScryptonite-0.15-F8W9M5THBW4FIZAr1UOHUh.a: unhandled ELF relocation(RelA) type 42

ihaskell: ihaskell: unable to load package `cryptonite-0.15'
[I 17:42:00.371 NotebookApp] KernelRestarter: restarting kernel (1/5)
[W 17:42:02.181 NotebookApp] Timeout waiting for kernel_info reply from b074f8aa-5097-4890-b5b8-69f6037966e4
ihaskell: /home/user/.stack/snapshots/x86_64-linux/lts-6.2/7.10.3/lib/x86_64-linux-ghc-7.10.3/cryptonite-0.15-F8W9M5THBW4FIZAr1UOHUh/libHScryptonite-0.15-F8W9M5THBW4FIZAr1UOHUh.a: unhandled ELF relocation(RelA) type 42
```

**Comment by peddie** [comment] 2016-06-10 00:32
This now works for me on x86_64 with LTS 6.2 and anaconda's python distribution.  Thanks!

**Comment by peddie** [comment] 2016-06-10 00:41
If I run `ihaskell install --stack` so that I can use other libraries I've installed with `stack`, I get the same error:

```
ihaskell: /home/peddie/.stack/snapshots/x86_64-linux/lts-6.0/7.10.3/lib/x86_64-linux-ghc-7.10.3/cryptonite-0.15-F8W9M5THBW4FIZAr1UOHUh/libHScryptonite-0.15-F8W9M5THBW4FIZAr1UOHUh.a: unhandled ELF relocation(RelA) type 42

ihaskell: ihaskell: unable to load package `cryptonite-0.15'
```

I'm not sure what you can learn from the fact that passing `--stack` makes the difference.

**Comment by gibiansky** [comment] 2016-06-10 21:39
It means that the non-stack environment you are using has the problem, whereas the stack one doesn't, since those are two different environments potentially.

This is likely related to duplicate package installations somehow rather than an IHaskell bug; if you google for 'haskell "unable to load package"' you get tons of these issues happening with ghci. 

I cannot reproduce this myself at the moment. However, things that may help:

- `ghc-pkg check` to find out if there's anything weird going on
- `ghc-pkg unregister` all IHaskell related packages and reinstall
- Make sure you have *exactly* one setup, not two or more: try not to mix cabal, stack, and Haskell platform. My suggestion is to stick just with stack for managing all your packages and GHCs; at some point I spent half an hour removing all traces of Haskell from my machine and then reinstalled it via stack *only* and that can help.

If you can reproduce this on a clean environment please let me know how to do so.

**Comment by Shimuuar** [comment] 2016-06-10 22:54
I also had same problem with missing relocation with hmatrix. It looks like problem arise when library has some C in it. I'll try to reproduce isdue tomorrow with 6.2

**Comment by Shimuuar** [comment] 2016-06-11 20:52
Nothing changed in lts-6.2 with respect to lts-5.17. I've used GHC-7.10.3 binaries from http://haskell.org/ghc for Debian. 

 - stack-1.0.4.3, no ghc-options: **unhandled ELF relocation**
 - stack-1.0.4.3  `cryptonite: -opta-Wa,-mrelax-relocations=no`: **works**
 - stack-1.1.2 with or without ghc-options: **unhandled ELF relocation**

Also any attempt to call function from hmatrix results in 
```
ihaskell: /home/alexey/.stack/snapshots/x86_64-linux/lts-6.2/7.10.3/lib/x86_64-linux-ghc-7.10.3/hmatrix-0.17.0.2-48ekk5lFtSc42AbtSb4jyz/libHShmatrix-0.17.0.2-48ekk5lFtSc42AbtSb4jyz.a: unhandled ELF relocation(RelA) type 42
```

Does anyone know what `unhandled ELF relocation(RelA) type 42` error mean? It's obviously related to linking but I have no idea beyond that

**Comment by Shimuuar** [comment] 2016-06-11 21:06
Same happens with sqlite-simple or I guess any package which calls C functions

**Comment by gibiansky** [comment] 2016-06-12 00:14
Strange. Seems like a linking problem. 

related to: https://github.com/DanielG/ghc-mod/issues/762#issuecomment-213743585
and: https://github.com/gibiansky/IHaskell/pull/660

I wonder what the difference between the different `stack`s is.

@Shimuuar Can you write a series of steps and commands (as detailed as you remember them, in whatever order you did them) to install everything you have installed and reproduce this issue? I would like to get this issue working inside a Docker container and then I might be able to debug it.

**Comment by Shimuuar** [comment] 2016-06-12 17:17
Sure I'll try to do it.

**Comment by gibiansky** [comment] 2016-06-12 17:35
Thanks, I appreciate the effort and help.

On Sun, Jun 12, 2016 at 10:17 AM Aleksey Khudyakov <notifications@github.com>
wrote:

> Sure I'll try to do it.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/gibiansky/IHaskell/issues/636#issuecomment-225448914>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABx2w6TpVZ32N9gugxJkVn2NqT9348Pmks5qLD8agaJpZM4HWYso>
> .
>
-- 

– Andrew

**Comment by peddie** [comment] 2016-06-13 01:27
> It means that the non-stack environment you are using has the problem, whereas the stack one doesn't, since those are two different environments potentially.

I've installed everything using only `stack` (LTS 6.2), including using the GHC it provides, yet when I pass `--stack` to `ihaskell install`, I encounter the linking problem.  Does this count as a "clean installation?"

I will also see if any of the linked issues make a difference.

**Comment by Shimuuar** [comment] 2016-06-13 16:05
I also suspect that bug depends on sufficiently new `ld` and/or `as`. Here is quote from https://github.com/DanielG/ghc-mod/issues/762#issuecomment-213743585

> The source of this problem seems to be that gas >= 2.26 uses some new relocation types (in particular type 42, aka R_X86_64_REX_GOTPCRELX), which are not supported by ghc's linker. As a workaround, these relocation types can be disabled by invoking ghc with the flag -opta-Wa,-mrelax-relocations=no

I have ld and as both 2.26. Maybe you don't have this bug because you have older version, Also @peddie which versions of as and ld do you use?

**Comment by peddie** [comment] 2016-06-14 01:57
@Shimuuar, good find -- I also have version 2.26 of both programs.  But it seems like you noticed above that passing the flags you quoted don't always fix the problem.

**Comment by gibiansky** [comment] 2016-06-14 02:00
Huh. Yes, I do not have 2.26 – I develop on OS X which uses `as` shipped with LLVM (`gas` is not installed). 

One random idea -- try compiling `cryptonite` with `-fllvm`? And maybe IHaskell as well? (Or whatever packages give you linking issues like this)

**Comment by peddie** [comment] 2016-06-14 03:26
I added

```
ghc-options:
  cryptonite: -fllvm
  ihaskell: -fllvm
```

to my `stack.yaml`, and stack told me that the `cryptonite` and `ihaskell` packages were being rebuilt.  I got exactly the same result (`unhandled ELF relocation(relA) type 42` / `unable to load package 'cryptonite-0.15'`).

**Comment by Shimuuar** [comment] 2016-06-14 11:18
> I develop on OS X 

Does OS X uses ELF executable format? Quick googling shows it doesn't. If so it could be impossible to reproduce bug on OS X at all. After all error message mentions ELF explicitly `unhandled ELF relocation(RelA) type 42`

**Comment by gibiansky** [comment] 2016-06-14 19:29
Yeah, that's why I mentioned that – I doubt I will be able to reproduce this, without, perhaps, a Docker image. 

More info here as well: https://ghc.haskell.org/trac/ghc/ticket/12147
Including a suggested workaround by @thomasjm 

Does the workaround work for you folks, @peddie @Shimuuar ?

**Comment by peddie** [comment] 2016-06-15 04:34
@gibiansky, I can't find any information in the help messages, documentation site or IRC channel about how to get stack to build dynamically linked executables.  I tried passing `--ghc-options -dynamic` to `stack install`, and I tried setting `-dynamic -rdynamic` in the `ghc-options` field of my `stack.yaml`, but the resulting `ihaskell` executables are bit-identical to the one I built without any of these options.  So it seems I haven't successfully applied the workaround -- do you know how to apply the equivalent of cabal's `--enable-executable-dynamic` (suggested on the trac ticket) using stack?

Passing `-opta-Wa,-mrelax-relocations=no` doesn't fix anything either, incidentally.

I appreciate the help so far.  I'll try any more suggestions you've got!

**Comment by AaronFriel** [comment] 2016-06-25 21:31
Everyone: I have found and fixed this issue, if you build Stack from my fork here: https://github.com/aaronfriel/stack you will be able to add `config.yaml` and `stack.yaml` options like so:

```
apply-ghc-options: everything
ghc-options:
  "*": -opta-Wa,-mrelax-relocations=no
```

And then you can force any packages that are causing trouble to rebuild with:

```
stack exec -- ghc-pkg unregister $PACKAGENAME --force
```

Substituting $PACKAGENAME for the package causing a problem, of course :)

To build and install my fork, just:

```
git clone https://github.com/AaronFriel/stack.git
cd ./stack
stack install
```

**Comment by peddie** [comment] 2016-06-30 17:32
@AaronFriel, nice job, and thanks for sharing your work.  It looks like in the end the problem was an interaction between a bug in GHC and a bug in Stack that prevented us from applying the workaround to the GHC bug?  

Unfortunately I'm not ready to support a custom fork of Stack for everyone in the environment where I was hoping to use IHaskell, so I'll have to wait until your changes make it into an upstream release.

**Comment by AaronFriel** [comment] 2016-07-11 16:07
@peddie: You got it. The custom fork is just this change: https://github.com/AaronFriel/stack/commit/675f834b2ea46963206d48cd84ec19efa833040a

**Comment by xavier83** [comment] 2016-08-02 17:34
So which version of stack/lts can i expect it to work out of the box?

**Comment by mgsloan** [comment] 2016-08-03 01:14
@AaronFriel 's patch is in stack HEAD

**Comment by vaibhavsagar** [comment] 2017-06-25 03:07
This patch is in Stack 1.4.0, closing this.

**Closed by vaibhavsagar** 2017-06-25 03:07 UTC
