### ISSUE TITLE
Kernel takes on the order of 10 seconds to warm up

### ISSUE THREAD

**Issue by benzrf** [gibiansky/IHaskell#865] opened 2018-05-27 18:37 UTC
If I make a new notebook and evaluate something simple like `3` or `"a"`, it will take on the order of 10 seconds for the kernel to respond. Once it does, however, it seems to subsequently work fine.

I tried installing with profiling enabled and then manually compiling `Main.hs`, and I got [some profiling information](https://benzrf.com/uploads/cf00a56c9737e08a.prof) (warning: 4.6M file). The most relevant info:
```
                                                                                                               individual      inherited
COST CENTRE    MODULE                    SRC                                               no.      entries  %time %alloc   %time %alloc
  interpret    IHaskell.Eval.Evaluate    src/IHaskell/Eval/Evaluate.hs:(166,1)-(187,28)     3102         1   88.6    3.4    99.5   96.3
```

I'm running IHaskell via Nix by using the `ihaskell-notebook` command from a shell launched with `nix-shell -p 'ihaskell.override {inherit (haskell.packages.ghc802) ghcWithPackages;}'`. (Strictly, the profiling info I dumped was in a slightly different environment where I'd added one or two packages and had enabled profiling, but the issue is similar (or worse) in the listed environment.)

**Comment by vaibhavsagar** [comment] 2018-05-28 00:34
It's not surprising that a lot of time is spent in `interpret` when that is what actually ends up interpreting Haskell code. Maybe the [initialisation](https://github.com/gibiansky/IHaskell/blob/560ccbf15be2f711b40abf5e61400cbc7093f137/main/Main.hs#L175-L195) code is contributing to the slow startup time?

**Comment by benzrf** [comment] 2018-05-28 15:12
This profiling info is from *only* starting the kernel and then evaluating `3` and then shutting down the kernel, so it should accurately reflect the startup cost (I think!).

**Comment by benzrf** [comment] 2018-05-29 14:57
I guess I could try, but the profiling information does say that it was about 80% in `interpret` *non-inherited*, meaning that the time was being spent somewhere that isn't listed anywhere else.

**Comment by vaibhavsagar** [comment] 2018-05-29 15:09
Makes sense! I'm seeing more like 3 seconds on my machine though, can you try [this](https://github.com/vaibhavsagar/notebooks/tree/fe4685d90581e584a71e114df161f9f52cacab0f/tarjan) and see if you are still getting ~10 second startup times?

**Comment by vaibhavsagar** [comment] 2018-06-02 09:01
I've merged my change into `master` now, so you can try that if you'd like. You sound pretty convinced that `runghc` fixes the slow startup you're experiencing, but I don't have any idea why that might be the cause or how we would make use of this knowledge to speed up IHaskell.

**Comment by benzrf** [comment] 2018-06-03 02:03
To be clear, the difference is probably interpreted vs. compiled mode, not the `runghc` binary in particular. I would've tried by running it from GHCi too, but then it complains about stdin stuff.

**Comment by vaibhavsagar** [comment] 2018-06-03 06:48
I gathered as much :smiley:, and I find it strange that interpreted is faster than compiled. IHaskell dynamically invokes the GHC API to interpret code, so maybe the mismatch between a compiled IHaskell and interpreted code is the cause of the slowdown you're experiencing? Additionally, is this something you notice every time you run a cell or only on startup?

**Comment by benzrf** [comment] 2018-06-03 15:22
There's a lot of variance, including in the amount of time startup takes. Some cells incur sudden lag, others don't—one thing that I noticed was that when I tried out the widgets library, the first time I tried to display a widget (er, maybe it was when I tried to *create* a widget? I can't remember, sorry) I got a massive delay.

I'll try out the branch later today, I think. Sorry for the delay.

**Comment by vaibhavsagar** [comment] 2018-06-03 15:53
To clarify: it's not a branch, it's my personal notebooks repo with pinned `nixpkgs` and `IHaskell` that takes closer to 3 seconds to start up (on my machine) instead of ~10. I'm also curious how using GHC 8.0 differs from using GHC 8.2 and *why* this is actually happening so if it's something that I can fix then I can make sure everyone gets to use a faster IHaskell (I don't think telling everyone to run it in interpreted mode is a good solution).

**Comment by benzrf** [comment] 2018-06-04 13:45
No dice—still takes forever to start up :(

**Comment by benzrf** [comment] 2018-06-04 13:46
Just tried the version with `cryptonite`. No dice—still takes forever to start up :(

**Comment by vaibhavsagar** [comment] 2018-08-20 10:26
I've run into something similar with GHC 8.6. Have you tried using the `--enable-executable-dynamic` with Cabal?

**Comment by vaibhavsagar** [comment] 2018-11-14 19:18
Closing this, please reopen if necessary.

**Closed by vaibhavsagar** 2018-11-14 19:18 UTC
