### ISSUE TITLE
try.jupiter.org IHaskell not work?

### ISSUE THREAD

**Issue by dabro** [gibiansky/IHaskell#703] opened 2016-11-22 21:31 UTC
Don't know if this is just me, but I've tried running IHaskell at [try.jupyter.org](try.jupyter.org) multiple times in the last two weeks, and have never gotten a reply back from wherever the kernel is running.  Input just stays '*' until the page reports a lost connection.

**Comment by typedeph** [comment] 2017-02-09 03:22
Wanted to second this. I try to execute any of the cells and nothing returns.

**Comment by tbenst** [comment] 2017-04-07 16:34
Confirmed. Times out on any cell

> A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

**Comment by Kludgy** [comment] 2017-06-02 23:42
Same here. Is this maintained anymore? Can I debug/contribute in any way?

**Comment by sumitsahrawat** [comment] 2017-06-03 11:20
Duplicate of #683.

**Closed by sumitsahrawat** 2017-06-03 11:20 UTC
