### ISSUE TITLE
Too many warnings when -Wall is set

### ISSUE THREAD

**Issue by sumitsahrawat** [gibiansky/IHaskell#613] opened 2015-12-05 21:03 UTC
```
$ jupyter console --kernel haskell         
Jupyter Console 4.0.2

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic

In [1]: :set -Wall

<interactive>:1:5: Warning: This binding for ‘it’ shadows the existing binding defined at <interactive>:1:1

<interactive>:1:5: Warning: Defined but not used: ‘pipe_var_77748799787913499675’

<interactive>:1:5: Warning: This binding for ‘it_var_77748799787913499675’ shadows the existing binding defined at <interactive>:1:5

<interactive>:1:5: Warning: This binding for ‘it’ shadows the existing binding defined at <interactive>:1:1

In [2]: map (+1) [1..5]

<interactive>:1:5: Warning: This binding for ‘it’ shadows the existing binding defined at <interactive>:1:1

<interactive>:1:5: Warning: Defined but not used: ‘pipe_var_22949703872331401261’

<interactive>:1:1: Warning:
    Defaulting the following constraint(s) to type ‘Integer’
      (Enum b0) arising from a use of ‘it’ at <interactive>:1:1-15
      (Num b0) arising from a use of ‘it’ at <interactive>:1:1-15
      (Show b0) arising from a use of ‘print’ at <interactive>:1:1-15
    In the first argument of ‘print’, namely ‘it’
    In a stmt of an interactive GHCi command: print it

<interactive>:1:5: Warning: This binding for ‘it_var_22949703872331401261’ shadows the existing binding defined at <interactive>:1:5

<interactive>:1:5: Warning: This binding for ‘it’ shadows the existing binding defined at <interactive>:1:1

<interactive>:1:5: Warning: This binding for ‘it’ shadows the existing binding defined at <interactive>:1:1

<interactive>:1:5: Warning: Defined but not used: ‘pipe_var_70387233140126141060’

<interactive>:1:5: Warning: This binding for ‘it_var_70387233140126141060’ shadows the existing binding defined at <interactive>:1:5

<interactive>:1:5: Warning: This binding for ‘it’ shadows the existing binding defined at <interactive>:1:1
[2,3,4,5,6]
```

**Comment by gibiansky** [comment] 2016-02-01 08:12
Dupe of https://github.com/gibiansky/IHaskell/issues/610

**Closed by gibiansky** 2016-02-01 08:12 UTC
