### ISSUE TITLE
ihaskell_labextension is not a valid extension: Missing extension module "lib/index.js"

### ISSUE THREAD

**Issue by oscarvarto** [gibiansky/IHaskell#907] opened 2018-08-18 02:58 UTC
I tried to install the jupyter-lab extension with instructions given in the README: https://github.com/gibiansky/IHaskell#linux
`jupyter labextension install ihaskell_labextension`

But I get the following message (error at the bottom):
```
jupyter labextension install ihaskell_labextension                                     ✔  377  21:51:51 
> /usr/bin/npm pack /home/oscarvarto/gitRepos/IHaskell/ihaskell_labextension
npm notice 
npm notice 📦  ihaskell_jupyterlab@0.0.6
npm notice === Tarball Contents === 
npm notice 1.2kB package.json   
npm notice 466B  README.md      
npm notice 0     style/index.css
npm notice === Tarball Details === 
npm notice name:          ihaskell_jupyterlab                     
npm notice version:       0.0.6                                   
npm notice filename:      ihaskell_jupyterlab-0.0.6.tgz           
npm notice package size:  881 B                                   
npm notice unpacked size: 1.7 kB                                  
npm notice shasum:        75877263ba7e1597e99f688acc60c98ff322a87b
npm notice integrity:     sha512-AJQkT3cFq2PP1[...]6oOjZPDrFXsJQ==
npm notice total files:   3                                       
npm notice 
ihaskell_jupyterlab-0.0.6.tgz

Errored, use --debug for full output:
ValueError: "/home/oscarvarto/gitRepos/IHaskell/ihaskell_labextension" is not a valid extension:
Missing extension module "lib/index.js"
```

I am using Anaconda's Python 3.6.6 on Ubuntu 18.04, and I get the same error with nodejs installed from official's distro channel and nodejs 10.x with ppa installed from https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions.

**Comment by vaibhavsagar** [comment] 2018-08-18 04:32
I don't know much about the JupyterLab stuff, maybe @MMesch has some ideas?

**Comment by MMesch** [comment] 2018-08-22 09:39
Hi @oscarvarto , can you try:

```
jupyter labextension install ihaskell_jupyterlab
```

(it will install from the online repository)

to install from source you have to go into the `ihaskell_labextension` directory and type:

```
npm build
npm install
jupyter labextension install .
```

I'll change the README and the extension name soon ...

**Comment by oscarvarto** [comment] 2018-08-24 18:50
If I follow your suggestion, then it hangs on a line saying:
```
ihaskell_jupyterlab@file:../extensions/ihaskell_jupyterlab-0.0.6-8f7e2b964370415138fbd71796de1e2b20edeec3.tgz
```

So, the above doesn't seem to fix the problem.

**Comment by ashwinvis** [comment] 2018-08-26 15:34
I think the problem is jupyterlab starting from v0.34 has upgraded to yarn v1.9.4 which enables node v10 packages. So until the extension is updated, one can use `pip install "jupyterlab<0.34"`.

**Comment by aaronaddleman** [comment] 2018-08-26 17:59
What version of JuypterLab is required for running IHaskell ?

**Comment by MMesch** [comment] 2018-08-26 18:06
I just renamed (to follow jupyterlab standards) and updated the extension for `0.34` (`jupyter labextension install jupyterlab-ihaskell`). There is another bug apparently with `0.34` in the kernel ... so I'll wait until I fixed it with the PR ...

**Comment by MMesch** [comment] 2018-08-26 18:08
it seems that we need constant dependency updates until jupyterlab reaches version 1.0.0, we can then just follow the major version number.

**Comment by ashwinvis** [comment] 2018-12-13 03:45
@MMesch your npm package seem to install fine, but results in an error while running

```
Bad interface file: /home/avmo/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.3/lib/ghc-8.4.3/template-haskell-2.13.0.0/Language/Haskell/TH.hi
    mismatched interface file versions (wanted "8044", got "8043")
```

I am using `jupyterlab==0.34.12`. Does it work for you? I couldn't find the changes you made on github.

**Comment by vaibhavsagar** [comment] 2018-12-13 04:03
I think you're using an old resolver in `~/.stack/global-project/stack.yaml`. Please update it and try again.

**Comment by ashwinvis** [comment] 2018-12-17 18:10
Thanks, it is working again! Updated to `resolver: lts-12.19`

**Comment by vaibhavsagar** [comment] 2018-12-17 18:33
Great, closing this.

**Closed by vaibhavsagar** 2018-12-17 18:33 UTC
