### ISSUE TITLE
Configuring extra-lib-dirs in stack.yaml to build on macOS

### ISSUE THREAD

**Issue by egnha** [gibiansky/IHaskell#1081] opened 2019-08-02 10:51 UTC
To work around the build error `Undefined symbols for architecture x86_64` on macOS 10.14 (Mojave), I had to add the following config to stack.yaml:
```
extra-lib-dirs:
  - /usr/lib
```
Would it make sense to add a note about this to README.md?

**Comment by vaibhavsagar** [comment] 2019-08-02 16:33
I don't have enough information to say. What was the cause of your error?

**Comment by egnha** [comment] 2019-08-02 17:07
Unfortunately, I no longer have the build log to give more context about the exact problem, apart from the quoted error message. But I do know that adding the config entry enabled the build to succeed. Can you reproduce it? (Assuming you're on a Mac.)

In the absence of more context, a parenthetical remark in the README might still be useful, I think, say something along the lines of "(If the install hangs with `Undefined symbols for architecture x86_64`, try adding ... to stack.yaml.)"

**Comment by vaibhavsagar** [comment] 2019-08-02 17:52
Did you install with Homebrew, like the README recommends? I don't have a Mac to test on.

**Comment by egnha** [comment] 2019-08-03 08:55
That makes sense. Maybe you are right and my particular mix of Homebrew + conda dependencies was the culprit ...

For the record, I installed the dependencies that I didn't already have (installed with Homebrew) into a conda environment, since I didn't want to install the Python dependencies, in particular Jupyter, into the (global) Python installation, as would have happened had I executed `pip install` as instructed in the README. My dependencies were installed like this:

- Homebrew: zeromq, cairo, pkg-config
- Conda: python, pango, libmagic, dependencies in requirements.txt

**Comment by essandess** [comment] 2019-09-07 13:11
This is a known `iconv` issue on macOS when conflicting `iconv` libraries are installed. See https://github.com/gibiansky/IHaskell/issues/1061, https://github.com/macports/macports-ports/pull/5050#issuecomment-525912731.

You just have to do what's necessary to make sure that the linker finds `/usr/lib` first. Unfortunately, the available options are tricky to debug. See https://github.com/macports/macports-ports/pull/5050#issuecomment-525906666.

**Comment by vaibhavsagar** [comment] 2019-10-05 22:15
Closing this.

**Closed by vaibhavsagar** 2019-10-05 22:15 UTC
